inferno/callbacks.py
inferno/dataset.py
inferno/net.py
inferno/tests/conftest.py
inferno/tests/test_callbacks.py
inferno/utils.py

I believe that especially if one looks at the changes in `net.py`, the new changes should result in cleaner user code.

rework callbacks

---

inferno/net.py

Resolve #9: Make fit non-optional by default

---

inferno/dataset.py
inferno/tests/test_dataset.py

Fix a bug that occurred when using float cv split in conjunction with stratfied and y=None.

Bugfix in CVSplit

---

README.md
environment.yml
inferno/dataset.py

@ottonemo 
Before merging, could you please update the environment.yml to include new pytorch version (I can't because I install via pip not conda).

Feature/simplify code pytorch 0.2

---

inferno/net.py
inferno/tests/test_net.py

by using `cold_start=False` or `partial_fit`

Make it possible to continue training 

---

inferno/callbacks.py
inferno/net.py
inferno/tests/conftest.py
inferno/tests/test_callbacks.py
inferno/tests/test_net.py

@ottonemo what do you think of the changes? If they are good, I will go ahead and replace old `Scoring` with new `WholesomeScoring` (including tests). Don't merge yet.

Simplify printlog and scoring

---

README.md

post1 had some crashes when loading in conjunction with ipython / tensorflow / zmq etc., post3 fixes these issues.

update to newer version of wheel file

---

inferno/callbacks.py
inferno/net.py
inferno/tests/test_callbacks.py
notebooks/Basic_Usage.ipynb

Verbosity is now a parameter on `NeuralNet`. It has not much use besides `PrintLog` and a single print statement in `NeuralNet`. However, it is really necessary for sane grid searches.
The example notebook just shows some basic usage. It should be extended in the future, and some content may be moved to an "extended usage" notebook.

verbosity and example notebook

---

inferno/net.py

Can be enabled by supplying a value to the `gradient_clip` parameter.
The norm type can be set using `gradient_clip_norm`.

Implement gradient clipping option

---

skorch/callbacks.py
skorch/tests/test_callbacks.py

Add checkpointing callback

---

skorch/net.py

Moved `default_callbacks` to `get_default_callbacks()`

Resolve #13

---

skorch/net.py
skorch/tests/test_net.py

Raise a more useful error if unknown arg passed.

---

MANIFEST.in
setup.py
skorch/__init__.py

Do some things for packaging

---

skorch/net.py
skorch/tests/test_net.py

Disable CUDA on load/unpickle if not available

---

docs/user/neuralnet.rst
skorch/net.py
skorch/tests/test_net.py

Allow passing dataset arguments to NeuralNet

---

environment.yml
requirements.txt
setup.py
skorch/callbacks.py
skorch/tests/test_callbacks.py

Useful when training time between epochs is quite long.

Introduce ProgressBar callback

---

skorch/net.py

Benefits:
- Consistency with valid_step
- Consistency when using more than one optimizer

Remove optimizer parameter from train_step

---

notebooks/MNIST.ipynb

Main idea: use sci-kit learn for data processing and skorch/pytorch for neural-networks.
Contains:
- A simple dense NN
- A CNN

MNIST example for skorch

---

docs/helper.rst
docs/index.rst
docs/skorch.rst
docs/user/FAQ.rst
docs/user/helper.rst
notebooks/Advanced_Usage.ipynb
skorch/helper.py
skorch/tests/test_helper.py

If this is approved, I would add an example somewhere first before merging.

Add helper SliceDict to simplify work with sklearn.

---

skorch/dataset.py
skorch/helper.py
skorch/net.py
skorch/tests/test_dataset.py
skorch/tests/test_net.py

Forwarded to net.module_.forward and net.train_split.

Support for fit_params

---

docs/user/callbacks.rst
skorch/callbacks.py
skorch/net.py
skorch/tests/conftest.py
skorch/tests/test_callbacks.py
skorch/tests/test_dataset.py
skorch/tests/test_helper.py
skorch/tests/test_net.py

* Refactor unit tests to reduce code duplication
* add `on_grad_computed` method to callbacks
* add `GradientNormClipping` callback
* deprecate old gradient clipping parameters
* update documentation and tests
Adresses #139

on grad computed callback

---

skorch/callbacks.py
skorch/net.py
skorch/tests/test_dataset.py

Use `get_len` instead of `len` to correctly handle dictionaries as input.

Resolve #142

---

skorch/net.py

Continued in https://github.com/dnouri/skorch/pull/149

on_batch_end now also gets 'y_pred' and 'loss'

---

Dockerfile
docker-compose.yml
requirements.txt
skorch/__init__.py
skorch/lr_scheduler.py
skorch/tests/test_lr_scheduler.py

This is my first open source project merge request. Sorry if it is rough around the edges:
- Added support to Pytorch learning rate schedulers as callbacks;
- Added WarmRestartLR from "SGDR: Stochastic Gradient Descent with Warm Restarts" https://arxiv.org/abs/1608.03983  (Pytorch issue  #3740);
- Added Dockerfile and docker-compose files to allow testing skorch without installing;

Learn rate schedulers

---

Dockerfile
examples/translation/Dockerfile
examples/translation/docker-compose.yml

We should think about setting up an automatic docker cloud build as well.

Base Dockerfile and specific one for example

---

skorch/callbacks.py
skorch/net.py
skorch/tests/test_callbacks.py

This makes it far easier to do simple filtering on specific
parameters for some quick development work.

on_grad_computed gets more generic named_parameters

---

skorch/callbacks/lr_scheduler.py

Refactor initialization code in warm restart sched

---

skorch/net.py
skorch/tests/test_net.py

Change forward/forward_iter's location to device

---

README.rst

Update install instruction for pytorch 0.4 in README.

---

docs/user/callbacks.rst
skorch/callbacks/base.py
skorch/net.py
skorch/tests/test_callbacks.py
skorch/tests/test_net.py

Addresses #175 and #148\, supersedes #178\.
Additionally, fixes several bugs related to `get_params` and `set_params` that were discovered during the changes.

fix problem with callback params

---

pylintrc
skorch/callbacks/__init__.py
skorch/callbacks/logging.py
skorch/callbacks/lr_scheduler.py
skorch/callbacks/scoring.py
skorch/net.py
skorch/tests/test_dataset.py
skorch/tests/test_lr_scheduler.py
skorch/tests/test_net.py
skorch/tests/test_utils.py
skorch/utils.py

Mostly docstrings, indentation, ...

Non-functional cleanups and pylint satisfaction.

---

skorch/callbacks/scoring.py
skorch/tests/callbacks/test_scoring.py

ENH: Enable sklearn make_scorer

---

docs/user/FAQ.rst

Add an answer to FAQ that explains how to use sample_weight.

---

skorch/net.py
skorch/tests/test_net.py

ENH: batch_size=-1 uses whole dataset

---

docs/user/REST.rst
examples/rnn_classifer/model.py
examples/rnn_classifer/palladium-config.py

A tutorial on how to use Palladium and Skorch to fit, persist, and serve a Pytorch model on the web.
Uses the RNN classifier notebook example.
Requires this fairly recent Palladium PR to function: https://github.com/ottogroup/palladium/pull/86

Tutorial on how to use Skorch together with Palladium

---

skorch/net.py
skorch/tests/test_net.py
skorch/utils.py

I didn't manage to push on the existing PR, so here is a new one -- sorry for that.

Tpietruszka feature/support optimizers requiring closure arguments

---

examples/benchmarks/mnist.py
skorch/net.py

This is most probably(tm) not needed anymore.

Remove superfluous data call

---

skorch/tests/callbacks/test_training.py

Small fix (`NeuralNetRegressor` was moved up a level)

TST: Fixes warning

---

skorch/callbacks/lr_scheduler.py
skorch/tests/callbacks/test_lr_scheduler.py

Resolves #266
I have been using code similar to this PR to plot learning rates. Hope you find it useful!
Edit: It won't work with `ReduceLROnPlateau` because of the metrics argument.

ENH: Adds simulation to lr_scheduler

---

skorch/helper.py
skorch/tests/test_helper.py
skorch/utils.py

Allows filtered_optimizer to be pickled.

BUG: Adds pickle support to filtered_optimizer

---

skorch/callbacks/logging.py
skorch/tests/callbacks/test_logging.py

Fixes https://github.com/dnouri/skorch/issues/284.

ENH: Always adds batches to keys_ignored

---

docs/user/FAQ.rst
skorch/helper.py
skorch/tests/test_helper.py
skorch/tests/test_net.py
skorch/utils.py

Fixes https://github.com/dnouri/skorch/issues/282

ENH: Adds predefined_split

---

skorch/dataset.py
skorch/net.py
skorch/tests/test_helper.py
skorch/tests/test_net.py
skorch/utils.py

* Remove deprecations related to use_cuda/device
* Add a missing space in error message.
* Improve docstring of to_tensor.
* Cosmetic: Add missing space after colon.
Addresses #250

Clean ups for release 0.3

---

docs/user/tutorials.rst
notebooks/Transfer_Learning.ipynb

1. Adds Transfer learning tutorial to readthedocs. 
2. Fix comment about training on gpu.

DOC: Add reference  to notebook in docs

---

skorch/callbacks/lr_scheduler.py
skorch/tests/callbacks/test_lr_scheduler.py

Fixes a small bug with `LRScheduler.simulate`.

BUG: Fixes learning rate simulate

---

README.rst

* Remove `torch` import (unused)
* Import `NeuralNetClassifier` from `skorch` (moved away from `skorch.net`)

Fix imports in the basic README example

---

docs/user/FAQ.rst
docs/user/quickstart.rst

Fix imports in documentation

---

docs/requirements.txt

Fixes https://github.com/dnouri/skorch/issues/304
This seems to fix the issue with RTD. Here is the result of RTD using this branch:
https://readthedocs.org/projects/skorch-doc-test/builds/7647492/

[MRG] Fixes RTD

---

skorch/callbacks/logging.py

This PR fixes several issues that I discovered while working with `ProgressBar`. See individual commit messages for details.
I would also propose to change the default `batches_per_epoch` mode in `ProgressBar` to "auto". Is there any reason against this?

Fix a number issues with ProgressBar

---

docs/user/tutorials.rst
notebooks/Transfer_Learning.ipynb

Addresses some of #316
You can see how this works here: https://colab.research.google.com/github/thomasjpfan/skorch/blob/transfer-learning-colab/notebooks/Transfer_Learning.ipynb

DOC: Update to run in colab

---

docs/index.rst
docs/toy.rst
docs/user/toy.rst
skorch/tests/callbacks/test_logging.py
skorch/tests/callbacks/test_lr_scheduler.py
skorch/tests/callbacks/test_training.py
skorch/tests/conftest.py
skorch/tests/test_classifier.py
skorch/tests/test_dataset.py
skorch/tests/test_helper.py
skorch/tests/test_net.py
skorch/tests/test_regressor.py
skorch/tests/test_toy.py
skorch/toy.py

Adds a `toy.py` module that will contain "toy" functions and classes.
At the start, this is `MLPClassifier`, which is a generic multi-layer perceptron, Use this module in unit tests where possible.
Also, add a test that shows that `NeuralNetBinaryClassifier` learns when fitting.

Toy pytorch module

---

skorch/callbacks/training.py

This is a small refactor to `filter_parameters` to allow `named_parameters` to return an iterator. This reduces the memory usage by not having to allocate memory for a list.

MRG: Refactors Paramapper.filter_parameters to use iterator

---

skorch/net.py
skorch/tests/test_dataset.py
skorch/tests/test_helper.py
skorch/tests/test_history.py
skorch/tests/test_net.py

Fixes deprecation warnings from the CI: https://travis-ci.org/dnouri/skorch/jobs/433449639

TST: Fixes deprecation warnings

---

requirements-dev.txt
skorch/tests/test_classifier.py
skorch/tests/test_net.py
skorch/tests/test_regressor.py

TST: Less flakey tests

---

notebooks/Advanced_Usage.ipynb

Update MyDataset example in Advanced Usage

---

notebooks/Advanced_Usage.ipynb
notebooks/Basic_Usage.ipynb

Adds links to colab and github in the beginning of notebooks.

DOC: Add links to colab in notebook

---

docs/user/neuralnet.rst
docs/user/save_load.rst

This section is moved from NeuralNet chapter to Save & Load chapter,
where it is situated more appropriately. Leave a short description and
a reference in the NeuralNet chapter.

Move section on model persistence to save & load chapter.

---

docs/user/save_load.rst

This PR adds small changes to make the doc easier to follow.

DOC: Minor fixes to save load doc

---

examples/word_language_model/data.py
skorch/callbacks/lr_scheduler.py
skorch/callbacks/scoring.py
skorch/callbacks/training.py
skorch/classifier.py
skorch/dataset.py
skorch/net.py
skorch/tests/test_classifier.py
skorch/tests/test_dataset.py
skorch/tests/test_helper.py
skorch/tests/test_history.py
skorch/tests/test_net.py
skorch/tests/test_regressor.py
skorch/tests/test_utils.py
skorch/toy.py
skorch/utils.py

Mostly to satisfy pylint. Also some minor refactorings to remove code
duplication (none of which affect public API) and addition of some
docstrings.

Non-functional code style changes.

---

README.rst

* some formulations
* mention that Python >= 3.5 is required

Minor updates in the README.rst.

---

skorch/toy.py

* Some default values that were not mentioned are now documented.
* The specific modules (classifier etc.) now have full docstrings (which is useful, e.g., when using IPython). Note: The parameters whose value shouldn't be changed are not documented (e.g. output nonlinearity for classifier).

Update docstrings in toy module.

---

CHANGES.md
skorch/net.py
skorch/setter.py
skorch/tests/test_net.py
skorch/tests/test_setter.py
skorch/utils.py

RFC: runtime parameter setting (e.g. LR)

---

README.rst

I propose to highlight some features in the README after the examples.
This is a WIP since the CLI PR is not merged yet.

Highlight some features in README

---

README.rst
docs/user/quickstart.rst

Small change in reference to #419

Highlight shuffling of training data

---

skorch/dataset.py
skorch/net.py
skorch/tests/test_net.py

Resolves #422 
Note: I successfully ran the `mnist.py` benchmark to check for performance regression.

Better error msg when dataset incompatible

---

docs/user/FAQ.rst
docs/user/dataset.rst

Further addresses https://github.com/dnouri/skorch/issues/422 by adding a FAQ item and rewording the `Dataset` docs.

DOC Adds FAQ entry on pytorch's Dataset

---

docs/user/save_load.rst

I did not use skorch for several months, so I had to catch up with the new features and read documentation. This PR make some minor improvements and clarifications to the "Using callbacks" section.

Improve "Using callbacks" documentation section

---

README.rst
docs/user/installation.rst
environment.yml

Fixes #460 
1. Add conda-forge to channels to install fire
2. Updates dependencies in environment.yml

DEP Fix installation issues

---

docs/user/FAQ.rst

Discussed streamline of the `sample_weight` example in FAQs.  See issue #203.

Streamlined the sample_weight docs example

---

notebooks/MNIST.ipynb

I was about to use the MNIST example as a testing ground for the SliceDataset PR when I stumbled over some issues I wanted to rectify first. As I went forward I thought that it wouldn't be a bad idea to add a few visual elements to the notebook, so I added the MNIST outputs.

Minor improvements to MNIST example

---

CHANGES.md
skorch/classifier.py
skorch/tests/test_classifier.py

BUG Adds eps to loss to prevent nans

---

skorch/callbacks/base.py
skorch/callbacks/lr_scheduler.py
skorch/classifier.py
skorch/cli.py
skorch/dataset.py
skorch/helper.py
skorch/history.py
skorch/net.py
skorch/regressor.py
skorch/tests/test_cli.py
skorch/tests/test_helper.py
skorch/tests/test_net.py
skorch/tests/test_utils.py
skorch/utils.py

No functional code changes except for removing `_make_optimizer`, which is not used in skorch code anymore.

Remove some linting errors that accumulated over time

---

docs/user/callbacks.rst

More hints for confused people like me. ;-)

DOC Docs on how to use learning rate schedulers

---

.travis.yml

Trying to fix issue in travis related to conda.

[WIP] Update Python versions of travis.yml

---

docs/conf.py
docs/user/FAQ.rst
docs/user/save_load.rst
pylintrc
skorch/callbacks/logging.py
skorch/helper.py
skorch/net.py

* Link to Python docs
* FAQ about setting dynamic input shape
* Improve documentation on save_params
* Add a link to EpochScoring in PrintLog
* Add missing new line before bullet list

Several additions to docs

---

skorch/callbacks/scoring.py

Move away from .scoring imports

---

docs/user/FAQ.rst

From https://stackoverflow.com/a/60170023/1643939

Update dynamic input FAQ with callback solution

---

.travis.yml
README.rst
pylintrc

For now, just an experiment to see if this works.

Test several pytorch versions in travis

---

CHANGES.md
skorch/dataset.py
skorch/tests/test_dataset.py

CVSplit raise warning when random_state is not used

---

.travis.yml
CHANGES.md
README.rst
docs/user/installation.rst

I did not actually test this locally, will just see if CI passes. But from the changelog of PyTorch, I didn't spot anything that we would need to change on the skorch side.

Support pytorch 1.5

---

docs/user/save_load.rst
docs/user/tutorials.rst
examples/nuclei_image_segmentation/Nuclei_Image_Segmentation.ipynb
notebooks/Transfer_Learning.ipynb
skorch/helper.py

In docstrings, docs, notebooks.

Remove a bunch of "neutral" networks

---

docs/index.rst

**What does this PR implement?**
It adds a BibTeX entry to use for citation purposes to the docs.
**Reference issues/PRs**
This closes #644.

Add citation information

---

README.rst
docs/user/installation.rst
environment.yml
scripts/deploy.sh

* conda install of requirements-dev.txt currently fails because of a
missing dependency, use pip instead
* update environment.yml, especially now containing pytorch, since
there is now a unified installation method
Further sections of the README and possibly docs need to be updated.

[WIP] Update README and enviroment

---

docs/user/neuralnet.rst

Fixes #672 
Until now, there was no one place where the different types of
possible input data were documented. Now there is an additional
section in the docs that covers that. Specifically, it talks about
regular data, Datasets, and multiple inputs.

Better document possible input data

---

README.rst

For talks, posters, blog posts etc.
Fixes #664

Add a section with external resources to README.rst

---

CHANGES.md
skorch/classifier.py

- CHANGES entry of latest merge was under wrong heading
- Changed its link to pointing to latest instead of stable (otherwise
only visible after next release)
- Replace spurious super class in `NeuralNetClassifier`

Fix 3 minor issues

---

.github/workflows/testing.yml
README.rst
docs/user/installation.rst

[PyTorch 1.9.0 release notes](https://github.com/pytorch/pytorch/releases/tag/v1.9.0)

Add support for PyTorch 1.9.0

---

CITATION

Hello 👋
This PR inserts the BibTeX snippet mentioned in [documentation](https://skorch.readthedocs.io/en/latest/?badge=latest) as its own file so it will be easy for someone to find on search engine I guess
Cheers!

Recommend citation

---

docs/callbacks.rst
docs/user/FAQ.rst
skorch/net.py

This should fix some of the zero result searches in the docs.
I left the FAQ entry for seeding open as this wasn't as easy to fix as the other cases.
I'll do a separate MR for this.

Address #834: Fix zero result searches

---

skorch/helper.py

Corrected Import for Python >=3.3

---

docs/user/FAQ.rst

Since skorch does not manage seeding it might still be helpful to guide users in the right direction and address some of the caveats of model vs. data seeding (i.e. how to fix the validation split or batch shuffling).

Address #834: Document random seeding

---

README.rst
docs/user/callbacks.rst
docs/user/installation.rst
docs/user/neuralnet.rst
docs/user/quickstart.rst
docs/user/save_load.rst
docs/user/tutorials.rst
skorch/net.py

I went through what I thought would be the most commonly visited parts of our documentation and made improvements when I saw the opportunity.
Mostly, this comes down to wording, adding information about changed/new features, adding links or fixing broken ones, etc., nothing major.

DOC Update the documentation in several places

---

README.rst

DOC: Add link to PyData Amsterdam slides

---

.github/workflows/testing.yml
README.rst
docs/user/installation.rst

Add PyTorch 2.3.0 to CI

---

notebooks/Learning_Rate_Scheduler.ipynb

I've updated the notebook to clarify about the training data being used in the notebook.
Could you please review the changes?
cc: @BenjaminBossan

Nit Fix in LR Scheduler Notebook
