inferno/net.py, inferno/tests/test_history.py
Before:
len(history[:, 'missing-key']) != len(history)
len(history[:, 'batches', 'missing-key']) == len(history)
Now:
len(history[:, 'missing-key']) != len(history)
len(history[:, 'batches', 'missing-key']) != len(history)
=> Make missing element handling consistent

inferno/__init__.py, inferno/dataset.py, inferno/net.py, inferno/tests/test_dataset.py
in classifier `fit(X, y=None)` causes problems:
-  for inputs with shape `(n,m)` as it will create `y` with shape `(n,1)` whereas shape `(n,)` would be needed
- for inputs with shape `(n,)` as it will try to access the length of each element to create appropriate dummy values (but the child is a number, not a sequence)
I added tests and a fix for these cases, although regression is still missing.
=> `y=None` causes trouble in many cases

inferno/tests/test_dataset.py
The reason was that `pytest.mark.skipif` is simply ignored when used in conjuction with a `pytest.fixture`.
=> Bugfix: pandas test not skipped

inferno/net.py, inferno/tests/test_net.py
It is now possible to pass an initialized torch module to NeuralNet (e.g. an nn.Sequential). Iff a param is set on that module, it is re-initialized.
Addresses #39
=> Feature: initialized modules

inferno/net.py, inferno/tests/test_net.py
This way, if we need `X` for the loss, we no longer need to re-implement `validation_step` and `train_step`.
=> get_loss method now also optionally takes the input data as argument.

inferno/dataset.py, inferno/net.py
Moreover, `train_split` was not documented.
=> Make dataset more useful

inferno/net.py, inferno/tests/test_net.py
This makes it possible to access the optimizer once the network is
initialized to make changes (e.g. changing the lr) during training
or to query the state of the optimizer.
This also makes it possible to continue training with the state
of the optimizer when doing partial fitting.
=> Move `get_optimizer` to `initialize_optimizer`

inferno/dataset.py, inferno/net.py
`get_iterator` is now called with `dataset` instead of X and y.
The advantage is that we don't redundantly initialize the stateless `Dataset`. If there is a costly transformation on X and y, it is now possible to perform it in the `transform` method of `Dataset` once before the fit loop, instead of performing it once at the start of each epoch.
I also expanded some of the docstrings.
=> Initialize Dataset only once per fit call

inferno/dataset.py, inferno/net.py, inferno/tests/test_dataset.py
It is passed to `(Stratified)ShuffleSplit` if that is used. Before this change, if a float is used with `CVSplit`, the split would be non-deterministic.
For the other cases, `random_state` is simply ignored, since `check_cv` does not take it as argument.
=> Allow CVSplit to take an optional random_state argument

setup.py
It should not have been in there, as usage with `pandas` is optional.
@ottonemo Please review.
=> pandas is not required in the setup.py and hence removed.

inferno/net.py, inferno/tests/test_net.py, inferno/utils.py
The problem was that `.cuda()` is called on a numpy scalar. To fix this, we have to wrap the scalar into a numpy array, but then `default_collate` will turn this into a n x 1 Tensor, which fails with `NLLLoss`. Consequently, `NeuralNetClassifier` intercepts n x 1 Tensors and flattens them.
@ottonemo pls review
=> Fix bug that occurs with classification and cuda.

inferno/exceptions.py, inferno/net.py, inferno/tests/test_net.py
Use `torch.load` so we can use the location mapping feature
which enables us to remap GPU storage to CPU storage.
=> Attempt at fixing #70

skorch/callbacks.py, skorch/net.py, skorch/tests/test_callbacks.py, skorch/tests/test_dataset.py, skorch/tests/test_net.py, skorch/utils.py
To achieve this, remove `use_cuda=False` as default argument.
Addresses #66
=> Ensure that `use_cuda` is passed to `to_var` and `to_tensor`

README.rst, notebooks/Advanced_Usage.ipynb, notebooks/Basic_Usage.ipynb, notebooks/README.md, skorch/net.py, skorch/tests/test_net.py
Mainly adds a regression task to the Basic_Usage notebook. I moved the "custom callbacks" section to an Advanced_Usage notebook, where we should put all the stuff that involves custom classes etc.
During the task, I discovered a bug in `NeuralNetRegressor`, which is fixed now.
This addresses phantom issue #77
=> Add more examples to notebook

skorch/utils.py
It is unusued as stated in #92.
=> Remove check_history_slice

skorch/net.py
It takes up a lot less memory to do
[n.argmax() for n in forward_iter()]
than doing
[n for n in forward_iter()].argmax()
especially when the probability vector is
high dimensional (10k+, e.g. word vectors).
=> Apply argmax batchwise in predict()

skorch/net.py, skorch/tests/test_utils.py, skorch/utils.py
Refactor `_get_params_for` to utility function. 
Makes it possible to use it in user code as well, e.g.
for assigning values in submodules, e.g.:
```python
def __init__(self, **kwargs):
self.submod = Submod(**params_for('submod', kwargs)
```
=> params_for utility

skorch/callbacks.py, skorch/tests/test_callbacks.py
The current solution is to not call `target_extractor`. That way, None is passed through, which will then lead sklearn to call the scoring function without y. Therefore, if the scoring function supports that, the user is fine.
The reason why `BatchScoring` does work here is because we currently replace non-existing y with a dummy tensor during batching. Of course, this is not ideal but not in the scope of this fix. It _may_ also solve itself with updates in pytorch.
=> Fix issue 112: EpochScoring flaky when y_test is None.

skorch/callbacks.py, skorch/tests/test_callbacks.py
Computes the batches per epoch automatically once training has started (on first epoch) but before the first computation is done. This is in contrast to the current 'count' method where we have to wait one epoch to know the proper number. While the latter is more stable, there are cases where we only train one epoch in total but still want a proper progress bar and don't necessarily know the number of batches per epoch beforehand (e.g. in a grid search scenario where we have the cv split but also a final run with the total number of training examples).
=> Add 'auto' parameter to progress bar

skorch/dataset.py, skorch/utils.py
Specifically, when conversion to torch tensor or to numpy array fails, users would often only get 
> `AttributeError`: bla has no attribute `.cuda`
Now a more specific `TypeError` is shown.
Is there a better way to test for a torch data type?
=> Better error message when data conversion fails.

skorch/net.py, skorch/tests/test_net.py
My proposal in #67 looks a little over-blown. Here is a more minimal __repr__ that focuses on the module parameters only. With the following module:
```
class MyClassifier(nn.Module):
def __init__(self, num_units=10, nonlin=F.relu):
super(MyClassifier, self).__init__()
self.dense0 = nn.Linear(20, num_units)
self.nonlin = nonlin
self.dropout = nn.Dropout(0.5)
self.dense1 = nn.Linear(num_units, 10)
self.output = nn.Linear(10, 2)
def forward(self, X):
X = self.nonlin(self.dense0(X))
X = self.dropout(X)
X = self.nonlin(self.dense1(X))
X = F.softmax(self.output(X))
return X
```
for an uninitialized net, the output looks like this:
```
<class 'skorch.net.NeuralNetClassifier'> (uninitialized) (
module=<class 'skorch.tests.test_net.MyClassifier'>,
module__num_units=42,
)
```
for the same, …
=> Add a minimally useful repr to NeuralNet.

README.rst
Should fix #129 
Know-how was taken from psutil [REDME.rst](https://raw.githubusercontent.com/giampaolo/psutil/master/README.rst) that has [well formatted page on pypi](https://pypi.python.org/pypi/psutil).
=> Correct README for PyPi [skip ci]

docs/user/neuralnet.rst, skorch/net.py, skorch/tests/conftest.py, skorch/tests/test_net.py
Addresses #141 and then some.
The following things were changed:
* Remove redundant `training` call in `forward_iter`
* There was no explicit test for `NeuralNet.foward` -- added it
* *breaking change*: `NeuralNet.predict` no longer performs argmax -- this makes only sense for a classifier, which `NeuralNet` isn't; as a consequence, `NeuralNetClassifier.predict` is now charged with taking the argmax.
* `NeuralNet.forward` can now deal with multiple outputs from `module_.forward`: If they are returned as a tuple, they are separated and `torch.cat` is called on each of them individually.
* `predict` and `predict_proba`  can now deal with multiple outputs from `module_.forward`: They discard all but the first output if outputs are tuples.
* Improve and adjust docstrings, documentation
Not …
=> Clean up of inference methods and allow multioutput

.travis.yml
Closes #104 
1. Caches conda packages.
2. Uses `pytorch-cpu` since travis-ci only has cpus for testing.
=> BLD: Caches conda pkgs in travisci

README.rst, docs/user/quickstart.rst
Addresses #161. Some stacks with 32 bit components (e.g. numpy)
may default to 32 bit integers for `y` in `make_classification`
but torch expects 64 bit values.
=> Explicitly cast y to 64 bit for 32 bit archs

skorch/net.py, skorch/tests/test_net.py
You can now pass a `location` paramter to `forward` which
indicates on which device to store the intermediate results.
=> Resolve #145 by implementing location parameter

skorch/callbacks/__init__.py, skorch/callbacks/logging.py, skorch/callbacks/lr_scheduler.py, skorch/net.py, skorch/tests/test_lr_scheduler.py, skorch/tests/test_net.py, skorch/utils.py
Closes https://github.com/dnouri/skorch/issues/168.
1. Adds `on_batch_begin` to `LRScheduler` to step through `CyclicLR`. This uses `len(net.history[-1, 'batches'])` to get the batch index for the current epoch. Once there are more than one epoch, the total number of batches per epoch is obtained by `len(net.history[-2, 'batches'])` . 
2. `CyclicLR` is a subclass of `_LRScheduler` which allows for `LRScheduler(CyclicLR)`.
3. Tests were refactored a little to use `@pytest.mark.parametrize`. Additional tests were added to confirm that `LRScheduler` is calling `step` or `batch_step`  the expected number of times.
=> ENH: Adds CyclicLR

README.rst, docs/user/neuralnet.rst, skorch/net.py, skorch/tests/test_net.py
This should hopefully avoid some confusion when another loss than `NLLLoss` is used. However, there will still be an error when using `NLLLoss` and having your module return log-probas.
Partially addresses #197\, #137\, #136
=> Classifier only applies log if nll loss

skorch/net.py
Default callbacks should now be part of a property
`_default_callbacks` for `get_params` to work. Furthermore, some
callbacks on `NeuralNet` were not initialized.
=> Fix bug where property _default_callbacks on NeuralNet was missing.

skorch/__init__.py
Closes #202 
This does require maintaining the minimum required torch version. I coded this as a `MIN_TORCH_VERSION` in `skorch/__init__.py`. Will that work?
I tested this with torch 0.3.1 and it threw the error. With torch 0.4.0 it didn't.
=> MAINT: enforce torch version

skorch/net.py, skorch/utils.py
Both of these callbacks retrieve already computed losses from the history, thus they do not need target and they do not need to process it in any way.
I care about this case for the following reason. I am implementing a multi-task network which has several outputs. The target values are actually dictionaries with the ground truth output for these several tasks. Naturally, I implemented a custom loss function which takes care of this. Now I expect the default scoring to be able to report training loss (because it was computed already). Right now it is not possible, because the default `target_extractor` is `to_numpy()`, which does not work with dictionaries (which my `y`s are).
In future the lambda can be replaced with Python [`noop()`](https://www.python.org/dev/peps/pep-0559/) built-in.
=> Default train/valid loss callbacks should have no-op target extractor

skorch/callbacks/scoring.py, skorch/tests/callbacks/test_scoring.py
Namely, when during the training process the training is finished
irregularly (e.g. through KeyboardInterrupt) when the net is still
cached, the caching would not be reset.
=> Fix a bug with caching that sometimes prevented infer to be reset.

skorch/callbacks/lr_scheduler.py, skorch/callbacks/training.py, skorch/tests/test_lr_scheduler.py
`LRScheduler` now allows you to monitor vars other than train_loss.
The class now takes a 'monitor' argument (like `Checkpoint`). If this is
a string, this value from the history is passed to step. If it is a
callable, the value returned by calling this callable with net is is
passed to step.
Moreover, some minor clean ups.
=> lr scheduler can now monitor other fields

skorch/callbacks/lr_scheduler.py, skorch/tests/test_lr_scheduler.py
The batch index should be zero indexed. Consider the following learning rate evolution of `CyclicLR`:
This PR moves the starting point from the red dot to the gray dot (on the bottom left).
=> BUG: Fixes off by one batch index

docs/user/neuralnet.rst, skorch/callbacks/scoring.py, skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
Adds saving and loading history from a `NeutralNet`.
This feature can be used by:
```python
before = NeuralNetClassifier(mymodule)
before.save_history('history.json')
before.fit(X, y)
after = NeuralNetClassifier(mymodule).initialize()
after.load_history('history.json')
```
Use Cases:
1. A user wants to continue training a `NeutralNet` while keeping the history of the previous run. This allows for `LRScheduler` to work correctly during the second run, since `LRScheduler` relies on `len(history)`.
2. After training is finished, the `history.json` file can be used to analyze the run.
=> ENH: Adds history loading and saving

docs/user/dataset.rst, docs/user/neuralnet.rst, skorch/dataset.py, skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
Resolves https://github.com/dnouri/skorch/issues/223.
1. Removes `to_tensor` and `self.device` from `Dataset`.
2. `torch.utils.data.DataLoader`'s `collate_fn=default_collate` function is able to handle our types without needing to covert them to tensors first. During training, validation, or evaluation, `NeuralNet.get_loss` and `NeuralNet.infer` will call `to_tensor` to move data to `self.device`.
3. When `X` and `y` are yielded from a `DataLoader`, their numerical values are already converted into tensors. `get_loss` and `infer` will call `to_tensor` with tensor-filled `X` and `y` values.  With this in mind, I refactored `to_tensor` to check the tensor type first and return early.
This PR frees `Dataset` from worrying about `device` and allows `NeutralNet` to handle device transfers. …
=> API: Removes device casting from Dataset

skorch/callbacks/scoring.py, skorch/dataset.py, skorch/net.py, skorch/utils.py
multi_indexing used to make a check of the data type for each
individual __getitem__ call, which is very slow because the DataLoader
will call with each index individually (instead of using a whole
slice).
Now skorch.dataset.Dataset will check the data type only once at
initialization, then provide multi_indexing with the correct indexing
function. This way, the check is only performed once per data.
@ottonemo pls review but don't merge yet (wait for #232)
=> Improve performance of multi_indexing.

docs/conf.py, docs/user/dataset.rst, docs/user/helper.rst, docs/user/neuralnet.rst, skorch/dataset.py, skorch/net.py
This PR contains a bunch of minor documentation fixes, see individual commit messages. Closes #238.
=> Documentation updates

docs/index.rst, docs/user/parallelism.rst, examples/rnn_classifer/dask-config.py, examples/rnn_classifer/palladium-config.py
Based on #237 
Work in progress, but please give me feedback.
Also explains how to use Palladium to run grid search in parallel.  This feature currently requires https://github.com/ottogroup/palladium/pull/87
=> Explain how to use Dask to parallelize grid search across GPUs

skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
Partially addresses #246.
I'm not particularly confident with unit testing in Python, so I probably did something wrong, please let me know.
=> Add support for configurable sink in Checkpoint

docs/requirements.txt
Updating the dependencies for doc building fixes syntax highlighting on readthedocs.
I tested this out by building this branch on readthedocs:
- **Before**: https://skorch.readthedocs.io/en/latest/user/quickstart.html#
- **After**: https://skorch-doc-test.readthedocs.io/en/doc-sytnax-fix/user/quickstart.html
Overall, there are little style changes that increases the contrast of elements.
=> DOC: Update deps to fix syntax highlighting

skorch/classifier.py, skorch/tests/callbacks/test_training.py, skorch/tests/test_classifier.py
Resolves #200. I made the following design choices when creating `NeuralNetBinaryClassifier`:
1. Uses `BCEWithLogitsLoss` by default, which means `self.module` must output the logit of probability. Based on the pytorch documentation, `BCEWithLogitsLoss` is more numerical stable to use than `BCELoss`.
2. `self.module` is expected to output values with shape: (`batch_size`, ). I am open to changing this to (`batch_size`, 1).
3. Subclassed `NeuralNetClassifier` since the `predict`, `predict_proba`, and `fit` docstrings are relevant for  `NeuralNetBinaryClassifier`. 
4. `NeuralNetClassifier.check_data` is reused, combined with a check on the y's dimension.
5. I had to override `get_loss` and use `NeuralNet.get_loss` instead. In its current form, `NeuralNetBinaryClassifier` should not need to …
=> ENH: Adds NeuralNetBinaryClassifier

skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
This PR includes an updated version of `CyclicLR` that allows more control of the step size. It adds an `step_size_2` to `CyclicLR`:
```python
step_size : int (default=2000)
Number of training iterations per for first half of a cycle.
Authors suggest setting step_size 2-8 x training iterations in epoch.
step_size_2 : int (default=None)
Number of training iterations per for second half of a cycle.
If step_size_2 is None, it is set to step_size.
```
For example with `step_size=3` and `step_size=17` the LR scheduling looks like this for one cycle:
There was used in recent paper that uses this LR scheduler for language modeling: https://arxiv.org/abs/1801.06146, where this technique increases the rate of convergence.
=> ENH: Adds more step_size control CyclicLR

skorch/callbacks/scoring.py, skorch/tests/callbacks/test_scoring.py
Fixes #267.
The scoring callbacks queries the history and updates `best_score_`  during `on_train_begin`.
This PR enables the following with proper `best_score_` tracking:
```python
net = NeuralNetClassifier(
module_cls,
...
)
net.fit(X, y)
net.save_params('params.h5')
net.save_history('history.json')
net.initialize()
net.load_params('params.h5')
net.load_history('history.json')
net.partial_fit(X, y)
```
=> ENH: Scoring uses best score from history

skorch/callbacks/scoring.py, skorch/tests/callbacks/test_scoring.py
(This fixes an issue introduced by #268.)
There might be a situation when history does not contain the column that the scoring callback writes to (and thus checks when loading).
Example: "valid_loss" scoring is added to the callback list by default, however it will not output anything to the history if there is no validation dataset (i.e. if `train_split=None`). Reloading such history will raise `KeyError`.
I updated the unit tests to reproduce exactly this situation. This updated test fails without the patch, and succeeds with.
=> Suppress KeyErrors when trying to load best index from history

docs/_static/css/my_theme.css
Adds logo in header for mobile. (The header turning blue didn't go with the gray side bar in desktop mode)
=> DOC: Adds logo in header for mobile

skorch/tests/callbacks/test_training.py
While working on other PRs, I noticed that `test_custom_scoring_nonstop` may fail randomly. For example this CI run: https://travis-ci.org/thomasjpfan/skorch/builds/404573466
This PR forces the scoring function to return strictly decreasing scores.
=> TST: Makes test deterministic

docs/user/history.rst, skorch/callbacks/logging.py, skorch/callbacks/training.py, skorch/tests/callbacks/test_logging.py, skorch/tests/callbacks/test_training.py
(This implements the ideas discussed in #246.)
`PrintLog` will output such columns on the right, just before 'dur'. When the value stored in history is True, a plus sign will be printed to the table. When the value stored in history is False or None, nothing will be printed, i.e. the cell will be empty.
The 'event_' prefix is stripped off from the key so as to not make the table header unnecessary long.
=> Add support for 'event_' columns in history

skorch/helper.py, skorch/utils.py
Adapts the style of `skorch.utils._make_split` by converting `skorch.utils.make_optimizer` to a private function.
=> RFC: Converts make_optimizer to a private func

docs/user/callbacks.rst, notebooks/Transfer_Learning.ipynb, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
This PR is a work in progress to add the features discussed in #289. I would like to get feedback before updating unit tests and documentation.
Some notes/discussion points:
* I dropped sink output for a bunch of reasons:
* Too verbose if all three targets are used
* Meaningless if target is a file-like object
* Would unnecessary complicate `save_model()`
* Now that we have events in the log I don't see much value in having it anyway
* This change may break existing code that did not explicitly specify argument names in constructor call. For example, `Checkpoint('model.pt', 'train_loss_best')` will now behave differently. Not sure how to deal with this other than introducing [keyword-only arguments](https://www.python.org/dev/peps/pep-3102/).
=> Support saving params, history, and pickling in Checkpoint

.travis.yml, Dockerfile, README.rst, docs/requirements.txt, notebooks/Advanced_Usage.ipynb, notebooks/Basic_Usage.ipynb, skorch/__init__.py, skorch/classifier.py, skorch/dataset.py, skorch/tests/test_classifier.py, skorch/tests/test_dataset.py, skorch/tests/test_net.py, skorch/utils.py
This PR updates skorch to support PyTorch 0.4.1. There is one small optimization to `skorch.utils. to_tensor` by using [`torch.as_tensor`](https://pytorch.org/docs/stable/torch.html#torch.as_tensor), which never copies unless necessary.
=> WIP: Update to 0.4.1

docs/user/callbacks.rst, skorch/net.py, skorch/tests/test_net.py
Callback names will be appended with a count suffix to
make the name unique if it appears more than once.
The suffix is of format `_{i}` with `i` starting at 1
with underscore as a separator to be addressable using
keywords arguments.
Example:
e1 = EpochScoring(name='a')
e2 = EpochScoring(name='b')
net = Net(callbacks=[e1, e2]).initialize()
cbs = dict(net.callbacks_)
Results in:
cbs['EpochScoring_1'] == e1
cbs['EpochScoring_2'] == e2
This addresses #294.
=> On name conflict assign unique callback names

skorch/dataset.py, skorch/tests/test_dataset.py
Fixes a problem mentioned #305.
=> uses_placeholder_y should not require existence of "y" field

skorch/callbacks/lr_scheduler.py
Refactors `_get_batch_idx` to keep track of the batch index.
=> RFC: Creates batch_idx on first run

skorch/net.py, skorch/tests/test_net.py
Closes #317.
This needs review, hence the WIP label. I don't use `state_dict` as mentioned in https://github.com/dnouri/skorch/issues/317#issuecomment-414629936, and I coded to the test.
=> MAINT: make sure copy links weights and optimizer

skorch/tests/callbacks/test_logging.py, skorch/tests/callbacks/test_regularization.py, skorch/tests/callbacks/test_training.py
Standard `fixture` now supports yielding. `yield_fixture` has been deprecated since pytest 3.
See: https://docs.pytest.org/en/latest/yieldfixture.html
=> Replace yield_fixture with fixture

skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py
Fixes #319.
I decided to not follow the proposed approach. For testing I patch `tqdm` and check that the expected `total` (i.e. number of epochs) is passed to its constructor.
As for the implementation of "count" mode, I switched to checking the length of the "batches" list in the history. This will have and added benefit that "count" will work as expected when resuming training from saved model/history.
=> ProgressBar refactoring

skorch/net.py
This test is performed inside `get_dataset()` anyway.
=> Remove superfluous call to is_dataset()

skorch/net.py, skorch/tests/test_net.py
=> BUG: Uses OrderedDict for callbacks

.travis.yml
1. Forces travis ci to only cache the compressed packages.
2. Forces miniconda to use `TRAVIS_PYTHON_VERSION` when creating `skorch-env`.
=> BUG: Fix travis ci cache and adds python versioning

skorch/tests/test_utils.py, skorch/utils.py
Also, add a bunch of tests for to_tensor.
Partly addresses #325.
=> Make to_tensor work correctly with PackedSequence

.travis.yml, skorch/net.py, skorch/tests/test_net.py
There was nothing preventing the user from using skorch with Python 3.5 but some tests were not passing. This is fixed now.
=> Make tests work with Python 3.5

skorch/callbacks/scoring.py, skorch/tests/callbacks/test_scoring.py
With the old implementation, a lot of code needs to be duplicated if `on_epoch_end` is overridden, making it difficult for users to implement their own `EpochScoring`. This is greatly facilitated now (see unit test for an example).
=> Refactor epoch scoring easier subclassing

examples/benchmarks/history.py, skorch/history.py, skorch/tests/test_history.py
Instead unroll the successive indexing steps and perform them backwards, i.e. starting with batches and following with epochs.
This PR solves #306 and is an alternative to #310
=> Rewrite History to not use any recursion.

skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Fixes #363
This PR works because `ReduceLROnPlateru` only has two modes: `max` and `min`.
=> BUG: Fixes ReduceLROnPlateau when mode == max

notebooks/Transfer_Learning.ipynb, skorch/helper.py
Work in progress and open for discussion.
Updates notebooks that freeze parameters and deprecates `filtered_optimizer` et al.
=> deprecate filtered optimizer

skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
Before each of these functions had their own logic of
determining a fallback device if special devices such
as CUDA are not available. Now there is one common
way of handling this case.
=> Unify device handling in __setstate__ and load_params

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
Previously, when the net was already initialized, calling
set_params(lr=new_lr) didn't trigger a re-initialization because the
method only looked for optimizer__* parameters. However, lr is
indirectly also an optimizer parameter, so setting it must
reinitialize the optimizer.
=> Bugfix: Reinitialize optimizer when set_params is called with lr.

CHANGES.md, skorch/callbacks/scoring.py
When `train_loss_score` or `valid_loss_score` is set to be the `scoring` function, it already assumes that `train_loss` or `valid_loss` is already in the batch history. If the metric is not in the history, this will raise an `KeyError` which is ignored.
This PR checks for these scoring functions and returns early.
=> ENH: Early exit for train_loss_score and valid_loss_score already in history

notebooks/MNIST.ipynb
Addresses https://github.com/dnouri/skorch/issues/382
In sklearn `0.20.0`, there is a bug with caching `fetch_openml`. This issue is fixed in sklearn `master`. For the time being disabling cache will allow this notebook to run.
=> BUG: Disables cache in MNIST notebook

skorch/tests/test_helper.py
`filtered_optimizer` and `filter_requires_grad` will soon be removed in `0.5.0`. While we get there, this PR gets rid of the `DeprecationWarning` warnings when running tests.
=> TST: Asserts deprecation to remove warnings

CHANGES.md, skorch/net.py, skorch/tests/test_net.py, skorch/tests/test_utils.py, skorch/utils.py
Fixes https://github.com/dnouri/skorch/issues/378
=> ENH: Adds TeeGenerator for named_parameters

CHANGES.md, docs/user/save_load.rst, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
The default prefix for `TrainEndCheckpoint` is `final_`. This PR adjusts it to `train_end_` along with all the references to it.
=> RFC: Changes default fn_prefix in TrainEndCheckpoint to train_end_

CHANGES.md, skorch/helper.py, skorch/tests/test_helper.py
* Calling .copy() now correctly returns another SliceDict instead of a
dict.
* == should now work as long as values are numpy arrays or torch
tensors.
* raise an error when `fromkeys` is called. It is generally not useful
to use this method with SliceDicts.
=> Fixes bugs with copy and eq on SliceDict (#388).

CHANGES.md, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
Resolves #399
Updates some tests to use the `<monitor>_best` syntax for `Checkpoints`'s `monitor` parameter.
=> [MRG] Warn user when using possibly wrong checkpoint monitor

CHANGES.md, docs/user/dataset.rst, skorch/classifier.py, skorch/dataset.py, skorch/net.py, skorch/tests/test_dataset.py, skorch/tests/test_net.py, skorch/tests/test_utils.py, skorch/utils.py
Among other use cases, this allows to use transformers that return
sparse matrices in the model pipeline, e.g. sklearn's
`CountVectorizer`. Previously, data needed to be cast to dense arrays
before passing it to skorch.
Note that during batching, data is cast to dense because pytorch's
`DataLoader` cannot deal with sparse matrices. But even if it could, it
would be of little use because torch support for sparse arrays is very
incomplete at this time (e.g. nn.Linear does not work in
backwards). Still this allows to avoid having to cast a potentially
huge input sparse matrix to dense so the feature should be useful.
This PR also updates to_tensor to allow casting a scipy sparse matrix
to a torch sparse COO tensor when accept_sparse=True. Even though
skorch does not use this feature, it …
=> Add support for scipy sparse CSR matrices as input data.

.travis.yml, requirements.txt, skorch/tests/test_net.py
Originally, the tests only ran on python 3.6, since the `environment.yml` file fixes the python version to 3.6. This PR correctly tests for the different version of python.
`skorch/tests/test_net.py` had to be adjusted because of how `python 3.5` handles the ordering of parameters.
When newer versions of pytorch comes out we can add additional versions to the `env` item in the `.travis.yml` file.
=> [MRG] Adds test for pytorch 1.0

.travis.yml, CHANGES.md, docs/user/helper.rst, examples/cli/README.md, examples/cli/train.py, requirements-dev.txt, skorch/cli.py, skorch/helper.py, skorch/tests/test_cli.py
This feature adds functionality to build quick CLIs for scripts based on skorch. The intent is to encourage users to adopt skorch by reducing the boilerplate required to make experiments reproducible.
This basically leverages the features of [fire](https://github.com/google/python-fire) to automatically create CLIs. In combination with skorch, almost all possible model parameters are immediately available via the command line, without all the boilerplate typically required to parse the arguments. This way, things like `max_epochs`, `lr`, `device`, etc. are available for free. Moreover, all arguments on the module are also available as usual (say `module__num_units`).
Furthermore, if there are docstrings in the numpydoc format, those can be displayed via `--help`, again without any …
=> Feature: quick CLIs

.travis.yml, requirements.txt, setup.py
WIP to merge the requirements.txt and requirements in setup.py.
=> Attempt to merge setup dependencies

skorch/cli.py
Import fire and numpydoc libraries lazily in cli.py. This way, there is no error when in helper.py (which imports from cli.py) when these libraries are not installed.
=> Tests pass even when fire and numpydoc are not installed.

CHANGES.md, docs/user/FAQ.rst
Puts the information in https://github.com/dnouri/skorch/issues/376#issuecomment-433732676 into the FAQ.
=> [MRG] Adds FAQ regarding initialization behavior of NeuralNet

notebooks/Transfer_Learning.ipynb
Updates tutorial to use a class in `NeutralNet.__init__`.
=> [MRG] Update transform learning to use class in NeutralNet.__init__

skorch/net.py, skorch/tests/test_net.py
Fixes #436 
I had originally planned a more thorough rework of initialization messages (in #440) but this is more complicated than expected. Meanwhile, this at least fixes the reported bug.
=> Fix misleading message when calling fit on initialized net

CHANGES.md, skorch/callbacks/logging.py, skorch/callbacks/lr_scheduler.py, skorch/net.py, skorch/tests/callbacks/test_lr_scheduler.py, skorch/tests/test_net.py
Fixes https://github.com/dnouri/skorch/issues/418
=> [MRG] Adds Batch Count in History

CHANGES.md, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
Resolves https://github.com/skorch-dev/skorch/issues/459
This PR updates `TrainEndCheckpoint` to use class composition (instead of inheritance) when using `Checkpoint` methods.
=> [MRG] ENH Uses checkpoint internally

examples/nuclei_image_segmentation/requirements.txt
This is because of a github security note. 5.7.8 seems to be the most recent version of notebook. I haven't actually checked what changed but I assume that the notebook should still work as expected.
=> Increase notebook version to >=5.7.8 in nuclei example

skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Addresses some of https://github.com/skorch-dev/skorch/issues/467
- Updates LR scheduling to support Pytorch 1.1 (step is called at the end of a epoch)
- Deprecates skorch's CyclicLR
=> [MRG] ENH Updates schedulers for pytorch 1.1

CHANGES.md, docs/user/neuralnet.rst, skorch/__init__.py, skorch/classifier.py, skorch/regressor.py, skorch/tests/conftest.py, skorch/tests/test_classifier.py, skorch/tests/test_regressor.py
These changes make NeuralNetClassifier NeuralNetBinaryClassifier and NeuralNetRegressor inherit from sklearn.base.ClassifierMixin and sklearn.base.RegressorMixin to gives them a score method. While making these changes I encountered the error ```Cannot import 'NeuralNetBinaryClassifier'``` so i added it to the ```__init__``` file.  This is in response to the issue #469  that I opened.
Here are working examples showing the efficiency of my changes:
```
from sklearn.model_selection import train_test_split
from skorch import NeuralNetClassifier 
from torch import nn, optim, tensor, cuda, Tensor
import torch.nn.functional as F 
from skorch.dataset import Dataset
from skorch.helper import predefined_split
from sklearn.datasets import load_digits, load_breast_cancer
digits = load_digits() …
```
=> AttributeError: 'NeuralNetClassifier' object has no attribute 'score'

skorch/callbacks/lr_scheduler.py
When using the newest skorch version with torch 1.0.0 the following exception is thrown:
```
File "/projects/Code/models.py", line 8, in <module>
from skorch.callbacks import BatchScoring
File "/projects/Code/skorch/skorch/__init__.py", line 7, in <module>
from .net import NeuralNet
File "/projects/Code/skorch/skorch/net.py", line 14, in <module>
from skorch.callbacks import EpochTimer
File "/projects/Code/skorch/skorch/callbacks/__init__.py", line 14, in <module>
from .lr_scheduler import *
File "/projects/Code/skorch/skorch/callbacks/lr_scheduler.py", line 16, in <module>
from torch.optim.lr_scheduler import CyclicLR as TorchCyclicLR
ImportError: cannot import name 'CyclicLR'
```
Since 1.1.0 is not that old we should probably support 1.0.x for some time.
=> Be backward compatible with torch 1.0

README.rst
I found it useful to install skorch using conda-forge, and someone else might find it useful  too.
=> Link to conda-forge in Readme

CHANGES.md, skorch/classifier.py, skorch/net.py, skorch/tests/conftest.py, skorch/tests/test_classifier.py, skorch/tests/test_net.py, skorch/tests/test_regressor.py, skorch/utils.py
Fixes #487 
* Use check_is_fitted similar to what is used in sklearn, except that
a skorch.exceptions.NotInitializedError is raised.
* Only assumes the presence of 'module_' so that nets remain hackable,
except where a different attribute is specifically required.
* Re-wrote existing checks to now use check_is_fitted.
=> More helpful error message when predicting with unfitted net

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
Fixes #500 
This catches wrong keyword arguments such as `optimizerlr` or `iterator_train_shuffle` and suggests the correct name.
=> Check init arguments for missing dunder notation

CHANGES.md, docs/conf.py, docs/user/REST.rst, docs/user/callbacks.rst, docs/user/helper.rst, docs/user/installation.rst, docs/user/tutorials.rst, examples/nuclei_image_segmentation/README.md, notebooks/Advanced_Usage.ipynb, notebooks/Basic_Usage.ipynb, notebooks/MNIST-torchvision.ipynb, notebooks/MNIST.ipynb, notebooks/README.md, notebooks/Transfer_Learning.ipynb, setup.py, skorch/net.py, skorch/tests/test_net.py
The following url prefixes where changed :
Old: https://colab.research.google.com/github/dnouri
New: https://colab.research.google.com/github/skorch-dev/
Old: https://github.com/dnouri/skorch
New: https://github.com/skorch-dev/skorch
Old: https://nbviewer.jupyter.org/github/dnouri
New: https://nbviewer.jupyter.org/github/skorch-dev
=> Updated all referenecs to old github repo #479

skorch/callbacks/lr_scheduler.py
The warning was pretty ambiguous.  First, you may think that you
should use torch.optim.lr_scheduler.CyclicLR as the net's optimizer,
which will fail.  Second, you may think that you can use
torch.optim.lr_scheduler.CyclicLR as a callback, which will obviously
fail, too.  I'm hoping this will save someone some time.  :-)
=> Tiny bit of more info in the CyclicLR deprecation warning 😅

CHANGES.md, docs/user/FAQ.rst, skorch/net.py, skorch/tests/test_net.py
In #506, there was a discussion about how to implement gradient accumulation with skorch. Unfortunately, it seemed to me that it is not easily possible. However, I believe that a small number of tweaks are enough to make it possible:
* move `self.optimizer_.zero_grad()` from `train_step_single` to `train_step` (might break some code but only of very advanced users)
* since `step` can now be None for train in `fit_loop`, add a conditional to only record things if step is not None (ugly but not back breaking)
I hope that this actually does what I read about gradient accumulation, since I have never used it myself. Maybe @fabiocapsouza can comment on that.
Overall, if this should really be enough, I think the changes would be worth implementing, given that popular architectures like BERT use …
=> Small changes to net that make grad accumulation easier

docs/user/parallelism.rst, examples/rnn_classifer/dask-config.py
I present to you: "the new way".
The old way now fails in a very awkward way and I had to find out the hard way.  `joblib` defines a thread global to carry the current active "parallel backend".  Now, imagine what happens when you set the backend using `sklearn.externals.joblib.parallel_backend`, but at runtime scikit-learn will happily use the unchanged backend defined in `joblib`.  I guess yay for vendoring packages?
=> DOC Update parallelism example to work with latest sklearn and dask

skorch/callbacks/scoring.py
This PR removes the use of the private `_score` function and calls the scorer directly.
=> MAINT Calls scorer directly

examples/benchmarks/mnist.py
Fix #423 by removing the `examples/datasets` folder.
This is done by using sklearn's `fetch_openml` and using the
default download path (caching will be done that way).
Also fixes a typo in the result.
=> Remove misleading datasets folder in examples

CHANGES.md, skorch/classifier.py, skorch/tests/test_classifier.py
Previously y_infer.squeeze() removed all dimensions with single entries,
which does not correspond to the docstring description. Instead, remove
only the last dimension, if it contains a single entry.
=> Fix squeeze inside NeuralNetBinaryClassifier.infer

skorch/callbacks/scoring.py, skorch/tests/callbacks/test_scoring.py
Introduces fix for issue #542 informing the user of the incompatibility in regards to multi-metric evaluation with scikit-learn.
=> Raise helpful error if dict passed to scoring callback

skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
With PyTorch 1.1.0 the optimizer step order was fixed (see af04b559445a76da33a2750ff630dee2749402d3) and a warning is issued when the order is violated. Since some LR scheduler tests don't call the optimizer at all this warning is falsely issued. We can fix this by calling `optimizer.step` anyway.
Relates to #467 and #561.
=> Fix wrongful LR scheduler step order warnings

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
Closes https://github.com/skorch-dev/skorch/issues/497
This updates `NeuralNet.load_params` with a checkpoint initializes when needed
=> ENH Load_params with a checkpoint initializes when needed

CHANGES.md, pylintrc, skorch/callbacks/lr_scheduler.py, skorch/callbacks/scoring.py, skorch/tests/test_utils.py, skorch/utils.py
Currently, skorch won't work with sklearn 0.22 because some code was changed that is more geared towards sklearn-internal use, which we, however, relied upon.
A list of failures:
1. `check_is_fitted` was changed (see #570) in a way that we won't raise a `NotInitializedError` anymore despite the net not being initialized. This is now solved by basically porting the old `check_is_fitted` behavior to skorch.
2. `safe_indexing` was changed (probably [here](https://github.com/scikit-learn/scikit-learn/pull/14475)) in a way that it no longer works with tuples as indices; the following code works in sklearn 0.21 but not in 0.22:
```python
from sklearn.utils import safe_indexing  # or _safe_indexing
import numpy as np
X = np.zeros((5, 3))
i = ([2, 4, 1, 0, 3], [1, 0, 2, 2, 1])
safe_indexing(X, i) …
```
=> Bugfix: sklearn 0.22

skorch/tests/test_net.py, skorch/utils.py
Fixes https://github.com/skorch-dev/skorch/issues/577 by using:
```py
from distutils.version import LooseVersion
```
=> BUG Fixes version checks

skorch/net.py
For the third time, I found that I had to modify fit_loop (once for skipping some validation steps when doing few shot learning, an other time for a workaround of #245 ). Every time I'm a bit hesitant because it's a large function so my changes will likely break for new versions of skorch. I think this should be made a little cleaner + in addition there's a large chunk of duplicate code, which is bad practice. I think it should be split in 2 simple functions.
Nothing very important but it's a bit better. I also give `epoch` as argument because this is something I usually need and makes sense to give to a function that computes a single epoch (e.g. for logging).
=> CLEAN : rm duplicate code in fit_loop.

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
When a user adds a new "settable" attribute (i.e. that works with
`set_params`) whose names starts the same as an existing attribute (say
"optimizer_2"), and adds a corresponding argument (say
"optimizer_2__lr"), skorch will erroneously complain about this
argument because it thinks it belongs to the other
attribute ("optimizer" in this example). The added unit test should
illustrate this behavior.
=> Fix a bug with custom attribute name clashes

skorch/callbacks/__init__.py
The `TensorBoard` callback was missing from `__all__`, which led to it not being listed in the docs.
In addition, I sorted the list and changed it to only contain one item per line because it was getting confusing.
=> Add tensorboard to __all__ list

CHANGES.md, requirements-dev.txt, skorch/callbacks/__init__.py, skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py, skorch/tests/conftest.py
Add support for logging through Weights & Biases.
`WandbLogger` automatically logs metrics, model topology, gradients and best trained model.
Sample run: https://app.wandb.ai/borisd13/skorch/runs/1vs6725x?workspace=user-borisd13
You can switch tabs on the left and see computer resources, model graph, logged files, etc
=> Add logger to Weights & Biases

CHANGES.md, docs/user/FAQ.rst, docs/user/callbacks.rst, skorch/callbacks/__init__.py, skorch/callbacks/scoring.py, skorch/classifier.py, skorch/net.py, skorch/tests/callbacks/test_scoring.py, skorch/tests/test_net.py
As mentioned [here](https://github.com/skorch-dev/skorch/pull/593#issuecomment-586739727), I factored out the addition of `PassthroughScoring` from the PR #593 
Here is a copy of the reasoning:
----------
Currently, when adding new losses on a batch level, it's very fiddly to log them on an epoch level. You have to define a custom function that picks the right value from history and passes it through without modification, then add a BatchScoring callback that uses this mock scoring function, defines the name of the score again, and pass noop.
Here is the code before and after:
```python
...
self.history.record_batch('my_loss', my_loss)
...
from skorch.callbacks import BatchScoring
from skorch.utils import noop
def my_loss_score(net, X=None, y=None):
return net.history[-1, 'batches', -1, …
```
=> add PassthroughScoring

skorch/tests/callbacks/test_scoring.py
The test relied upon 75 samples being split into 60/15 for the
internal train/valid split. However, with certain sklearn versions,
the split would be 59/16 because of stratification. As a solution, the
target values are all set to 0. Since they are not important for the
tests, this solution works.
This is kinda blocking a release, as it affects the tests during the
release build.
=> Fix a failing test with sklearn 0.21.2

CHANGES.md, skorch/net.py, skorch/tests/conftest.py, skorch/tests/test_classifier.py, skorch/tests/test_net.py, skorch/tests/test_regressor.py
This change was announced in release 0.7 and now is a good time
to actually make the change. We just had a release, and since this
change could break existing code, we want it to be on master for
some time before making a new release.
This PR contains the main change and a bugfix that surfaced because
of the change.
Fixes #521
get_params no longer returns learnable parameters like module_. This
is in line with what sklearn expects but can potentially break old
code that relied on it implicitly. Since get_params is often uesd
under the hood in sklearn (e.g. by GridSearchCV), this could affect a
lot of code.
Still this new behavior is better so we decided to go along with
it. We had an announcement for 0.7 that warned about this. Now it's
coming in 0.9 (probably 1 year later or so, thus …
=> Change: new get params behavior and bugfix

CHANGES.md, skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Closes #610 
I could use some assistance with schedulers that update once an epoch:
`optim._LRScheduler` initializes with `self.last_epoch=0`. This means that if we're training for `0,1,2,3,4` epochs, the respective values for `last_epoch` at the end of every epoch (where we update LR) will be `1,2,3,4,5`. This requires changes I made in the tests:
`assert lr_policy.lr_scheduler_.last_epoch == max_epochs-1` => `assert lr_policy.lr_scheduler_.last_epoch == max_epochs`
The reason this seems to have worked until now is in fact because of what I think is a bug:
It seems like until now, inside `on_epoch_end`, `epoch=len(net.history)-1=>epoch=0`. This means  that when `self.lr_scheduler_.step(epoch)` is called for the first time, the scheduler does not actually take a step because …
=> [MRG] LRScheduler batch option

skorch/net.py
closes #565
Usually criterions in pytorch inherit from nn.Module, meaning that they should have a `self.training` option that says whether it is during train or validation. yet skorch does not update it. This is useful for cases where there are multiple losses and the weights of each loss change during training (but not testing). E.g. beta-vae with annealing, Gans ....
@BenjaminBossan
=> ENH : set train / valid of criterion.

CHANGES.md, skorch/tests/test_net.py
As discussed in #621.
Also: Add entry to CHANGES.md
ping @YannDubs
=> Add tests for criterion being set to train/valid

skorch/net.py
This is a follow up of the discussion in #596
The idea is for `get_params_for_optimizer` to to return 
`*args` and `**kwargs`, but that wasn't quite clear. This
is now clarified by the use of a tuple for `args`, names of
variables, and adjusted docstring.
=> Make intent of output of get_params_for_optimizer more explicit

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
This fixes a bug introduced by moving the `optimizer.zero_grad()` call
outside of the train step function, making it incompatible with LBFGS
and other optimizers that call the train step several times per
batch and expect the gradient to be reset after each call.
I extended the existing test for LBFGS to actually check the
training and validation scores after the fit call. With the
faulty behavior, the scores are actually diverging, and with the
bugfix, we get reasonable scores.
In #636, I wrote
> So we could introduce a parameter like perform_zero_grad_each_step=True or so (not a very nice name) and if a user wants to do their custom stuff with gradients, they need to turn it off.
After some thinking, I believe it's not actually necessary to
introduce an argument to turn off the …
=> Call zero grad on each train step

skorch/__init__.py, skorch/utils.py
In skorch 0.10.0, this Python version will no longer be officially supported.
Also, use correct import order in utils.py.
=> Raise a FutureWarning if Python version is < 3.6

skorch/classifier.py, skorch/tests/test_classifier.py
Only check `get_dim(y) != 1` if `X` is not a dataset.
=> Implements fix to #631

skorch/tests/test_utils.py, skorch/utils.py
dict like input is possible for user customized dataset or output function,but will get error in current code such as forward_iter 
And current to_tensor support dict input, but to_device doesn't support
=> Feature: support dict-like input for to_numpy and to_device

CHANGES.md, skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py
The fix is to ignore the tqdm instance in the returned state of
the progress bar callback.
=> Resolve #656 by fixing progressbar pickling

CHANGES.md, skorch/tests/test_utils.py, skorch/utils.py
The previous implementation of `to_device` would break when a
user decided to return a list of tensors in `forward`.
This patch applies `to_device` recursively and adds support
for lists in addition to tuples.
=> to_device: Handle nested lists/tuples recursively

CHANGES.md, docs/scoring.rst, docs/skorch.rst, docs/user/FAQ.rst, skorch/scoring.py, skorch/tests/test_scoring.py, skorch/utils.py
This addresses issue #628 . Tests could probably be more complete. @BenjaminBossan , please let me know if/how they could be fleshed out to be more comprehensive. 
As a side note, I have limited familiarity with `PassThroughScoring`, but it seemed, in a way, like overkill. This could be because I'm not properly understanding some edge cases. Anyway, at the time, I thought it was sensible to write an accumulator class that handles the reduction of the batch-level statistics for `criterion`. In case this isn't ideal, is there an easy way to convert the current code to something that uses Skorch tools (*e.g.,* `PassThroughScoring`)?
=> Implement loss scoring for #628

CHANGES.md, docs/user/neuralnet.rst, skorch/classifier.py, skorch/net.py, skorch/tests/test_classifier.py, skorch/tests/test_net.py, skorch/tests/test_utils.py, skorch/utils.py
Resolves #637, resolves #661
Supersedes #572 #580
Added a parameter `predict_nonlinearity` to `NeuralNet` which allows users to control the nonlinearity to be applied to the module output when calling `predict` and `predict_proba`. Also, when using `CrossEntropyLoss`, softmax is now automatically applied to the output.
This PR implements what was discussed in #661. Regarding the implementation, I used the most simple approach at the moment (no dispatching based on the net class, for instance). Also, I added a `get_predict_nonlinearity` method to `NeuralNet`, which handles the case of `'auto'` vs `None` vs `callable`.
Regarding the naming, I decided against `output_nonlinearity`. I believe `predict_nonlinearity` makes it much more obvious that this nonlinearity is **not** applied to the …
=> Add predict nonlinearity

CHANGES.md, skorch/callbacks/training.py, skorch/net.py, skorch/tests/callbacks/test_training.py, skorch/tests/test_net.py, skorch/utils.py
Solves #635 by implementing my proposal [here](https://github.com/skorch-dev/skorch/issues/635#issuecomment-628862698).
With this change, `save_params`, `Checkpoint` and `TrainEndCheckpoint` now support storing the criterion. But not only that, they support storing any custom pytorch module. So if the user has defined `net.mymodule_`, that can be saved by calling with `net.save_params(f_mymodule=...)`.
This change turned out to be more involved than initially thought:
* giving nice error messages is complicated with `**kwargs`
* we called the module argument `f_params` instead of `f_module`, whereas everything else is called `f_<attribute-name>`, so I had to handle that outlier
* I hadn't considered that `Checkpoint` and `TrainEndCheckpoint` were also affected
For these reasons, it took …
=> Feature save params arbitrary modules

.travis.yml, README.rst, docs/user/installation.rst, skorch/tests/test_classifier.py, skorch/tests/test_net.py, skorch/tests/test_regressor.py
Also document the support of that version.
@ottonemo tested PyTorch 1.6.0 with CUDA and it worked, so this should also work without further modification.
I wonder if we should start dropping support for older PyTorch versions. The main reason would be to accelerate CI. What are your thoughts?
=> Add PyTorch version 1.6.0 to .travis.yml

skorch/tests/test_net.py, skorch/utils.py
Fixes #681
This bug was introduced by PR #646 after a change in the function
signature of `utils._make_split`. Here the bug is fixed by returning to
the old signature but giving default values for `valid_ds` and `y`, so
that the desired behavior introduced by #646 is still possible.
A test is introduced to catch this bug.
As a cleanup, the unrelated test_predefined_split now uses the
already defined `dataset_cls` fixture instead of importing `Dataset` again.
@Dewald928 this should fix your bug. I tested your code example
and it worked.
=> Fix a TypeError that occurred when using predefined_split

examples/rnn_classifer/RNN_sentiment_classification.ipynb, notebooks/Advanced_Usage.ipynb, notebooks/Basic_Usage.ipynb
Make some improvements to a couple of notebooks. Fixes #599, fixes #691 
* For grid search, disable internal train-valid split. Add a comment
to explain this.
* Set torch random seeds
* set torch manual seeds
* always cast y to int64
* FunctionTransformer's validate is now False by default
* minor text adjustments
* set random seeds for torch (with cuda) and numpy
* add option for bidirectional RNNs
* add dropout to RNNs as well
* use dropout module instead of F.dropout (using the latter is a bug)
=> Multiple small improvements to notebooks

CHANGES.md, examples/cli/README.md, requirements-dev.txt, skorch/cli.py, skorch/tests/test_cli.py
Change cli helper so that normal (i.e. non-skorch) sklearn estimators
also work. This mainly required to relax the assumption that the
estimator must have a `module` attribute.
On top, added a comment about not using positional arguments for
functions parsed by fire. The problem is that internally,
this (silently) breaks fire, so that `python foo.py --help` does not
work and instead returns the result of `python foo.py -- --help`.
=> Make cli helper work with normal sklearn estimators

docs/user/neuralnet.rst
**Issue reference**: 
This is in reference to documentation issue https://github.com/skorch-dev/skorch/issues/696:
**What does it implement/fix**
I have added an example of using Python function for optimizer property where a user may need to use non-default PyTorch optimizer
=> Adding code example to use python function for optimizer property

skorch/net.py, skorch/tests/test_net.py
Check for iterator_train__shuffle=True and raise a UserWarning if found.
This is just a minor convenience feature for the user, to prevent unwanted consequences, as e.g. witnessed [here](https://github.com/skorch-dev/skorch/issues/601#issuecomment-653237672).
=> Warn if valid data is shuffled

skorch/tests/test_helper.py, skorch/tests/test_net.py
The argument is deprecated and will be removed in sklearn 0.24.
=> Remove iid argument from GridSearchCV

CHANGES.md, requirements-dev.txt, skorch/callbacks/__init__.py, skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py, skorch/tests/conftest.py
Similar to the existing Neptune logger, just logging to [Sacred](https://github.com/IDSIA/sacred) instead
of Neptune. The main difference is the name of the logging function and
that an experiment does not have to be closed explicitly. I kept the
documentation and functionality similar, to make it easier to use one as
a drop-in replacement for the other.
=> Add a logging callback for Sacred

CHANGES.md, docs/user/callbacks.rst, skorch/net.py, skorch/tests/callbacks/test_training.py, skorch/tests/test_net.py
**What does this PR implement?**
It allows disabling all callbacks with `callbacks=False`.
I ran into a use case that uselessly spent 97% of the training time in various callbacks with the default `callbacks=None`. After this PR with `callbacks=False`, it only spends 5% of the total training time in various callbacks, a rather drastic speedup.
=> API: allow disabling all callbacks

CHANGES.md, skorch/callbacks/lr_scheduler.py
The parameter was deprecated, see [1].
[1] https://github.com/pytorch/pytorch/blob/dee82ef3ea1ed2cae4e891f071adff03cb4a6e0d/torch/optim/lr_scheduler.py#L13
=> Remove the deprecated LRScheduler epoch parameter

.github/workflows/testing.yml, README.rst, docs/user/installation.rst, skorch/__init__.py, skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Supersedes #686 
- use github actions instead of travis
- add CI for PyTorch 1.4.0 (since we want to support 4 versions)
- check PyTorch 1.7.1 instead of 1.7.0
- update docs
- remove warning about Python 3.5 support
- remove warning about change in CyclicLR step being per epoch
=> Maintenance: python and pytorch versions updated

docs/requirements.txt
Build fails with message that Cython>=0.28.5 needs to be installed to build sklearn. Let's add this dependency.
=> Try to fix failing docs

docs/index.rst, docs/requirements.txt, docs/user/performance.rst
Documents a few was on how to reduce skorch overhead when fitting models.
Based on [this comment](https://github.com/skorch-dev/skorch/pull/730#issuecomment-748932720).
Also, no longer use outdated pytorch version for docs.
=> Add performance section to docs

docs/user/FAQ.rst
The code previously shown was just able to run on nets trained
on CPU, not GPUs.
=> Address #734: move sample weights to self.device

CHANGES.md, skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Closes https://github.com/skorch-dev/skorch/issues/363
=> FIX Makes sure score is passed to ReduceLROnPlateau

skorch/helper.py
**What does this PR implement?**
It fixes the class path in the example of predefined_split, using `skorch.dataset.Dataset` instead of `skorch.Dataset`
**Reference issues/PRs**
None
=> Docs: Fix class path in predefined_split example

CHANGES.md, skorch/history.py, skorch/tests/test_history.py
* Index epochs first so IndexError is always raised for bad epoch
indices, and so jagged batch counts don't raise a false IndexError.
* Only filter epochs with non-matching keys once, and do it after
indexing epochs to avoid returning values from the wrong epoch(s).
* Never compare arbitrary values to empty lists or tuples - instead,
generate _none if no batches matched the keys to exclude the epoch.
* Don't raise KeyError if all batches are requested but there are no
epochs - an empty list is probably more useful.
---
There are 8 new tests - 13 if you count all the parameterized variants.
Command used to run the new regression tests:
```
pytest --no-header --disable-warnings -c /dev/null skorch/tests/test_history_newtests.py
```
Tests included in test_history_newtests.py: …
=> history: Fix regressions in __getitem__

CHANGES.md, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
Fixes #773
Removes `__getattr__` from `TrainEndCheckpoint`. This should not be BC breaking because `Checkpoint` does not set attributes that is not already set in `TrainEndCheckpoint`.
Alternative to #774
=> FIX Allows TrainEndCheckpoint to be unpickled

skorch/net.py, skorch/tests/test_net.py
This is a bug introduced by a last minute change in #751 
After `clone`ing a net, `_module`, `_criteria`, and `_optimizers` are already
populated. Then, when loading params, there is yet another registration,
i.e. a double registration. As a consequence, there would be two
`'modules'` etc. This is a fix for that.
The solution is a two-pronged: Don't return `_modules` etc. when cloning,
and make a safety check during registration. Either of those should be
sufficient, but it's probably better to be extra safe.
=> Fix a bug that led to double-registration

skorch/net.py, skorch/tests/test_net.py
When a net's module references another of that net's modules, the former
will yield the latter's parameters. Therefore, when all parameters are
collected, the latter's parameters appear twice.
This bugfix consists of remembering all yielded parameters in a set and
not yielding those that were already encountered.
This bug was introduced very recently (#751) and should occur very
rarely, since modules don't typically reference each other.
=> Fix bug that could lead to duplicate params

skorch/tests/test_utils.py
This PR makes sure that CUDA tests can run. As stated in the [pack_padded_sequence](https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html?highlight=pack_padded_sequence#torch.nn.utils.rnn.pack_padded_sequence) docs, the lengths must be on the cpu.
With this PR, cuda tests can run and two tests will fail:
<details>
<summary>TestNeuralNet.test_pickle_load[False] </summary>
```
_________________________________________________ TestNeuralNet.test_pickle_load[False] __________________________________________________
self = <skorch.tests.test_net.TestNeuralNet object at 0x7f28a45b1970>, cuda_available = False                                             
pickled_cuda_net_path = 'skorch/tests/net_cuda.pkl' …
```
=> TST Fix test collection on cuda

skorch/classifier.py
Issue #802 
The original check_data method can only receive ndarray y-values because of np.unique function. Now the method is modified so that tensor y-values can be processed with torch.unique specifically.
=> Allow NeuralNetClassifier to fit tensor labels #802 

docs/requirements.txt, scripts/deploy.sh
Sphinx build is currently broken:
https://readthedocs.org/projects/skorch/builds/15141681/
I tried the fix of pinning docutils<0.18 suggested [here](https://github.yuuza.net/sphinx-doc/sphinx/issues/9727) and it works:
https://readthedocs.org/projects/skorch/builds/15141724/
The better long term solution would be to use a newer version of Sphinx but I haven't checked how to do that yet and I wouldn't be surprised if this surfaces some new problems, hence this short term solution for now.
(Please disregard the other commit in this PR.)
=> Docs: pin docutils to fix broken Sphinx build

CHANGES.md, skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
This PR is a proposition to solve the issue https://github.com/skorch-dev/skorch/issues/808
It adds a new argument to the EarlyStopping callback allowing to retrieve the best model after stopping the training (from `patience` epochs before the end of the training). This useful for most situations in which EarlyStopping is used and at the same time makes the skorch API more coherent with other user-friendly deeplearning libraries which also implement EarlyStopping callbacks (e.g. Keras).
=> Add `restore_best_weights` argument to EarlyStopping callback

.github/workflows/testing.yml, README.rst, docs/user/installation.rst
[PyTorch release notes](https://github.com/pytorch/pytorch/releases/tag/v1.10.0)
Update CI and documentation about officially supported PyTorch versions. It doesn't look like any other changes should be necessary.
=> Add torch 1.10.0 to CI, remove 1.6.0

.github/workflows/testing.yml, skorch/tests/test_net.py, skorch/tests/test_probabilistic.py
For some reason, gpytorch + PyTorch 1.8.1 now caused the following error:
> AttributeError: module 'torch.linalg' has no attribute 'cholesky_ex'
Thus, gpytorch tests are now skipped for that PyTorch version.
Also, no longer exclude 3.9 + 1.5.1, since 1.5.1 is no longer officially
supported and no longer tested.
=> Test excluding Python 3.7 + PyTorch 1.8.1

CHANGES.md, docs/user/FAQ.rst, examples/benchmarks/mnist.py, skorch/net.py, skorch/tests/callbacks/test_scoring.py, skorch/tests/test_net.py
At the moment, we initialize the iterators for the training and
validation datasets once per epoch. However, this is unnecessary and
creates an (ever so small) overhead.
With this PR, the iterators are created once per fit call only.
Theoretically, this could present a backwards compatibility issue, but I
think it will only affect very few, if any, users; those who are
affected should be able to fix the issue quickly.
I don't believe that anyone would rely on the iterators being
initialized once per epoch as a feature. If there is a good use case for
actually doing so, please tell me and we can discuss if this PR should
actually be rejected.
To test the change in terms of performance, I ran the MNIST benchmark.
(While doing so, I fixed a few issues with the script.). The difference
of …
=> Initialize iterator only once per fit call

CHANGES.md, docs/user/helper.rst, requirements-dev.txt, skorch/helper.py, skorch/net.py, skorch/tests/test_helper.py
Proposal to implement [huggingface accelerate](https://github.com/huggingface/accelerate) (#760). If this is adopted, we would probably no longer need implement AMP support, since this is a subset of the offered functionality of accelerate.
For lack of appropriate hardware, I could not test if this would actually work or not.
First idea was to implement this as a callback but that would require to add a lot of new `on_` -methods that would serve only this callback for now.
Therefore, this feature is implemented as a mixin class to serve as proof of concept of how this could look like if implemented in the `NeuralNet` class itself.
I'm not sure if we would need to use [`accelerator.utils.save`](https://github.com/huggingface/accelerate/blob/a5ea2a932ccb7c9c880d2151c7dfcb13a12ecc95/src/accel …
=> Experimental support for accelerate

skorch/helper.py, skorch/tests/test_helper.py
It is apparently recommended to "unwrap" the model after training ends:
https://github.com/huggingface/accelerate/blob/6ffab178accebda485295bddf8eb6bf436ff698f/src/accelerate/accelerator.py#L542-L551
https://github.com/huggingface/accelerate/blob/e549cea65ced232131d2d028717b6a0057274add/docs/source/quicktour.rst#savingloading-a-model
=> Unwrap accelerated model on train end

requirements-dev.txt, skorch/dataset.py, skorch/net.py, skorch/tests/test_dataset.py, skorch/tests/test_net.py, skorch/utils.py
Solves #838
The Huggingface transformers library (or, more precisely, the tokenizers
library) currently is possibly the most popular library for state of the
art NLP models. Therefore, it would be good if skorch works well with
transformers.
One of the key steps is tokenization. For this, tokenizers implements
their own classes that return a special data type, which is currently
not understood by skorch. This PR makes it so that skorch understands
and thus correctly works with that data type. Without this adjustment,
users would need to write some (light) wrapper code to make skorch work
with these tokenizers.
The problem with this special data type, `BatchEncoding`, is that it's a
`Mapping` but not a `dict`. skorch already deals with `dict`s but since
`Mapping`s are not instances of …
=> Facilitate integration with huggingface

.github/workflows/testing.yml, README.rst, docs/requirements.txt, docs/user/helper.rst, docs/user/installation.rst, docs/user/parallelism.rst, docs/user/probabilistic.rst, examples/cli/README.md, examples/nuclei_image_segmentation/README.md, scripts/deploy.sh, skorch/callbacks/logging.py, skorch/cli.py
- Drop 1.7.1
- Update 1.10.0/1.10.1 to 1.10.2
Moreover, change all pip install instructions from `pip install` to
`python -m pip install`, which is the recommended way.
=> Update to PyTorch 1.11.0

docs/user/quickstart.rst
Solves #830
By default, skorch uses softmax + `NLLLoss` for classification. This can
lead to numerical instability issues (when logits have large magnitude).
Therefore, mention in the docs how to prevent that issue.
=> Mention that softmax might lead to num instability

CHANGES.md, skorch/helper.py, skorch/tests/callbacks/test_all.py, skorch/tests/test_helper.py, skorch/tests/test_net.py, skorch/utils.py
The error message when using `set_params` with an invalid key has been
altered to contain quote marks. Now testing message without or with.
Using `SliceDataset` could result in an error because of this line:
https://github.com/skorch-dev/skorch/blob/090ece088803244659c6eb16876e84bf784967b7/skorch/classifier.py#L119
This would fail when y comes from a `SliceDataset`. However, the error was masked
because `GridSearchCV` swallows errors by default now. Therefore, we now run these
tests with `error='raise'` to surface the bug.
Regarding the bugfix, it is a bit clumsy because we need to make
`to_numpy` work with `SliceDataset`, but we cannot check
`'isinstance(X, SliceDataset)'`
because we don't want to import the helper class. Therefore, we now
check this indirectly by looking at attributes. …
=> Bugfix: sklearn 1.1 and SliceDataset

.github/workflows/testing.yml, requirements-dev.txt, setup.py, skorch/tests/test_net.py
No longer check Python 3.6 because it's been unsupported since the end of last year. Instead, add Python 3.10 to the CI. Unfortunately, the only PyTorch version supporting 3.10 right now is 1.11 (issue #66424), so all other versions are not being checked.
While working on this, an issue with wandb + protobuf came up, so I had to pin some versions there.
=> Check Python 3.10 in CI

.github/workflows/testing.yml, README.rst, docs/user/installation.rst
- add PyTorch 1.12.0 to CI
- drop PyTorch 1.8.1 from CI
There is nothing in the [release notes](https://pytorch.org/blog/pytorch-1.12-released/) to suggest that any further changes are needed on our side.
=> Update to PyTorch 1.12.0

skorch/callbacks/logging.py, skorch/callbacks/training.py, skorch/probabilistic.py
I fixed a couple of minor issues I found in the docs
- Added/removed some blank lines for consistency
- Some entries like 'event_' were interpreted as links, so I added code
markers around them.
- Added usage example to `TensorBoard` docstring
- Fixed a copy paste error in `WandbLogger`
- Some links were not parsed correctly, so I used different syntax
- Fixed issue in code example of `SacredLogger`
Additionally, I removed an outdated comment in `probabilistic.py` docstring.
What I would like to know: Is it possible to have blank lines inside
example code blocks without starting a completely new block? Some
examples are now very cramped and I would like to add some blank lines,
but don't know how.
Also, it looks like in the official docs, the API docs for `probabilistic.py` are empty: …
=> Docs: Fix issues callback docs

skorch/helper.py, skorch/tests/test_helper.py
Fixes #816
- Returning new instances now return the type of self instead of
hard-coding the class. This is necessary when users subclass these
classes, as otherwise, the subclass would return instances of the
parent class.
- Use super() without arguments.
=> Small fixes to SliceDict and SliceDataset

requirements-dev.txt, skorch/tests/test_helper.py
Latest changes in accelerate led to breaking tests. Unfortunately, the
solution is to use a privat method on AcceleratorState but the devs said
that this would be the best solution.
This PR also sets the requirements for accelerate to be v0.11 or higher.
This not only makes our code simpler, but also opens the door to
supporting gradient accumulation with accelerate (which will come in a
separate PR).
=> Fix broken tests with new accelerate version

skorch/tests/test_classifier.py, skorch/utils.py
Until now, `NeuralNetBinaryClassifier` assumes that `BCEWithLogitLoss` is used. Now, `BCELoss` works as well.
Note: Unless there is a very good reason not to, it's still recommended to use `NeuralNetClassifier`, even when dealing with a binary classification problem.
=> Make binary classifier work with BCELoss

skorch/helper.py, skorch/tests/test_helper.py
The latest accelerate release added gradient accumulation support. This
requires the AccelerateMixin to call the training loop within a context
manager. This is now done. Users can therefore use the gradient
accumulation feature of accelerate.
=> Support for gradient accumulation with accelerate

CHANGES.md, skorch/net.py, skorch/tests/test_net.py
In #600, we introduced the option to set `device=None`, which means that
skorch should not move any data to any device. However, this setting
introduced a bug when trying to load the net, as that code didn't
explicitly deal with `device=None.` With this PR, the bug is fixed.
If `device=None`, we really have no way of knowing what device to map the
parameters to. The most reasonable thing to do is to use the fallback,
which is 'cpu'.
=> Nets now can be loaded even if device=None

skorch/callbacks/training.py, skorch/tests/callbacks/test_training.py
When a key was monitored that was not found in history, the resulting
error message would be:
> skorch.exceptions.SkorchException: Monitor value 'Key
'valid_loss_best' was not found in history.' cannot be found in history.
Make sure you have validation data if you use validation scores for
checkpointing.
This bugfix now returns the correct error message.
=> Fix wrong error message in Checkpoint

skorch/tests/test_utils.py, skorch/utils.py
Ostensibly solves https://github.com/skorch-dev/skorch/issues/883, though I am not very familiar with this codebase.
=> Move mps data to CPU in util.to_numpy

examples/benchmarks/mnist.py, notebooks/MNIST.ipynb
The default was changed from numpy arrays to pandas dataframes, which
broke a notebook. Use parameter to return numpy arrays again.
Additionally, set random seed for shuffling in mnist benchmark script.
=> fetch_openml should return numpy arrays

CHANGES.md, requirements.txt, skorch/callbacks/scoring.py, skorch/tests/callbacks/test_lr_scheduler.py, skorch/tests/test_net.py, skorch/tests/test_probabilistic.py, skorch/utils.py
Remove version checks that are no longer required because we don't
support the min versions anymore.
I was working on the proposed solution in #887 when I noticed that none
of the version checks we do is actually required anymore. After removing
them, we thus no longer depend on distutils's `LooseVersion`.
If we ever need to do a version check in the future, I would still go
with the [scipy Version class](https://github.com/scipy/scipy/blob/main/scipy/_lib/_pep440.py).
Also, in the future, we should ensure to add `# TODO` comments to all
version checks so that we can easily find them.
One change I introduced here is to require scikit-learn>=1.0.0. I think
this should be fine because it's been out for some time now and it still
supports Python 3.7.
We could go to 0.24 instead and would …
=> Remove outdated version checks

skorch/_version.py, skorch/tests/test_probabilistic.py
_Just as we thought we could get rid of all version checks..._
GPyTorch requires relatively high versions of PyTorch. Therefore,
certain tests in the CI matrix may fail for certain GPyTorch versions.
We thus skip the GPyTorch tests in case the PyTorch version is not
sufficiently high.
We don't want to force the PyTorch version itself on the user (as long
as it's sufficiently high) because most users probably don't use
GPyTorch.
To check the versions, as discussed in #888, we use the version checking
code copied from scipy.
=> Skip GPyTorch tests if torch version too low

skorch/tests/test_hf.py
1. `xfail`ing test doesn't fail anymore (cloning now works)
2. delimiter needs to be `" "` for `tokenizers==v0.13`, other delimiters don't seem to work
=> Bugfix tests hf tokenizers

.github/workflows/test-hf-integration.yml, README.rst, scripts/hf-integration-tests.py
Solves #901
This PR adds a github workflow that runs integration tests with Hugging Face. These tests cover:
- using a pretrained tokenizer
- using a pretrained BERT model
- storing model artifacts on the HF model hub
The tests can be triggered manually [here](https://github.com/skorch-dev/skorch/actions) and additionally run once per week on Sundays at 9:00 AM UTC.
I'm not sure if we can really test if the workflow works before merging, any ideas?
=> Add Hugging Face integration tests

CHANGES.md, skorch/probabilistic.py, skorch/tests/test_probabilistic.py, skorch/utils.py
This is mostly relevant for CI, as most users probably don't have gpytorch installed.
The problem is that some gpytorch versions now raise an `AttributeError` with some torch versions. Since we try to import gpytorch in `utils.py` and in `test_probabilistic.py` but only catch `ImportError`, the `AttributeError` will be raised. However, the presence of an incompatible gpytorch version should not preclude the usage of skorch.
In the gpytorch tests themselves, we already check for compatible versions and skip if they are not compatible. However, to check versions, we first need to successfully import gpytorch, which fails.
Here is an example of a job that currently fails because of this:
https://github.com/skorch-dev/skorch/actions/runs/3421070263/jobs/5696711066
The solution now is to catch …
=> Don't fail when gpytorch import fails

scripts/deploy.sh
I ran into this issue when trying to deploy:
https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check
Therefore, I adjusted the script to update pyopenssl. On top of that, I was frustrated with the very slow testing cycle, since the script always creates a new environment from scratch. To accelerate this, I removed the reliance on the (outdated) `environment.yml` and used pip for the `requirements.txt`, which is faster and also more in line with our CI.
I tested this locally except for the last step (the upload) and it worked.
=> Update deploy.sh, openssl, use pip

.github/workflows/testing.yml, README.rst, docs/user/installation.rst, skorch/tests/test_helper.py, skorch/tests/test_hf.py
Remove 1.9.
Also, removed excluded combination from test matrix to check if they work now.
Locally, PyTorch 1.13 worked, and the change log also doesn't contain anything to suggest otherwise.
=> Update CI to use PyTorch 1.13

skorch/helper.py, skorch/tests/test_helper.py, skorch/tests/test_hf.py, skorch/tests/test_net.py, skorch/tests/test_probabilistic.py
The following changes were made:
1. don't use `torch.testing.assert_allclose`, use `torch.testing.assert_close` instead
2. don't use `np.bool`, use `bool` instead
3. fix test that uses ragged numpy array
Regarding 2, `np.dtype('bool') == bool`, so replacing `np.bool` by `bool` should just work.
Regarding 3, numpy used to allow creation of ragged arrays, e.g. `np.array([[1], [2, 2], [3, 3, 3]])`
This does not work anymore with newer numpy versions (tested on 1.24.0rc2). To make it work, `dtype=object` has to be passed explicitly. This does not affect any skorch code directly, but it was necessary to fix a test.
=> Fix FutureWarnings from numpy and torch

CHANGES.md, skorch/classifier.py, skorch/helper.py, skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
These bugfixes were originally provided in #912 but are now moved to their own PR.
1. Inferring the predict nonlinearity made the assumption that a `net.criterion_` exists. However, this might not always be the case. Now, this function works even if the criterion attribute has a different name. Moreover, when more than one criterion is defined, the identity function will be returned.
2. The second bug is that in `check_is_fitted`, we made the check dependent on the `module_` attribute. Again, we should not assume that it always exists, as users may define different names. Now, those custom names will be checked, and only if those don't exist is it assumed that the `module_` attribute should exist.
3. The `helper.py` module now defines an `__all__` attribute. This seems to be necessary for …
=> Bugfixes: Bugs stemming from the use of non-standard modules and criteria

docs/user/dataset.rst
skorch automatically unpacks dictionaries when passing input arguments to the module's `forward` method. Sometimes, this may not be wanted. This PR updates the docs to show how to prevent that.
The updated docs: https://skorch.readthedocs.io/en/docs-prevent-dict-unpacking/user/dataset.html#preventing-dictionary-unpacking
=> DOC: How to prevent dictionary unpacking in forward

skorch/tests/test_probabilistic.py
A couple of changes in GPyTorch v1.10 resulted in our tests failing. This PR fixes those tests. The actual integration has not changed, though, only tests.
Be aware that CI will broken until this PR is merged.
~The updated tests will now fail for GPyTorch v1.9 and and below. However, I think it is not worth it to write the tests in a backwards compatible manner. First of all, the GPyTorch integration does not appear to be widely used. Second, this only affects the tests, not the actual implementation, so normal users should have no issues. Developers would need to upgrade GPyTorch to avoid the error.~
I had to add code for backwards compatible tests after all because GPyTorch v1.10 is not available for Python 3.7, which we still test.
Initially, we had issues with GPyTorch kernels not …
=> Fix failing tests for GPyTorch v1.10

CHANGES.md, docs/user/history.rst, skorch/history.py, skorch/net.py, skorch/tests/test_history.py, skorch/tests/test_net.py, skorch/tests/test_probabilistic.py
(this is more or less copied from the docs)
When training a net in a distributed setting, e.g. when using `torch.nn.parallel.DistributedDataParallel`, directly or indirectly with the help of `AccelerateMixin`, the default history class should not be used. This is because each process will have its own history instance with no syncing happening between processes. Therefore, the information in the histories can diverge. When steering the training process through the histories, the resulting differences can cause trouble. When using early stopping, for instance, one process could receive the signal to stop but not the other.
`DistributedHistory` will take care of syncing the distributed batch information across processes, which will prevent the issue just described.
This class needs to be …
=> Add DistributedHistory for multi-gpu training

CHANGES.md, docs/user/history.rst, docs/user/huggingface.rst, examples/accelerate-multigpu/README.md, examples/accelerate-multigpu/run-no-skorch.py, examples/accelerate-multigpu/run-with-skorch.py, skorch/hf.py, skorch/tests/test_hf.py
Partly resolves #944
There is an issue with using skorch in a multi-GPU setting with accelerate. After some searching, it turns out there were two problems:
1. skorch did not call `accelerator.gather_for_metrics`, which resulted in `y_pred` not having the correct size. For more on this, consult the [accelerate docs](https://huggingface.co/docs/accelerate/quicktour#distributed-evaluation).
2. accelerate has an issue with being deepcopied, which happens for instance when using `GridSearchCV`. The problem is that some references get messed up, resulting in the `GradientState` of the `Accelerator` instance and of the dataloader to diverge. Therefore, the accelerator did not "know" when the last batch was encountered and was thus unable to remove the dummy samples added for multi-GPU …
=> Fix accelerate bug, document, add scripts

.readthedocs.yaml
Resolves #962 
Adding this `.readthedocs.yaml` makes the build [pass again](https://readthedocs.org/projects/skorch/builds/20584952/).
I'm not completely happy with this, because some of the configuration now lives in `.readthedocs.yaml`, and some is what we set on the admin panel of the web ui. It is not clear to me what takes precedence when. Ideally, we should migrate to rely solely on `.readthedocs.yaml` but I don't think it's possible. For example, automation rules cannot be specified on the yaml (https://github.com/readthedocs/readthedocs.org/issues/8287). Therefore, if the build error can be fixed without adding a `.readthedocs.yaml`, I'd prefer that.
=> FIX/DOC: Fix failing readthedocs build

docs/requirements.txt
Adding tabulate to the doc requirements seems to fix the broken API docs reported in #967.
Here is an example page on latest that is currently broken: https://skorch.readthedocs.io/en/latest/callbacks.html
Here is the same page on this branch which is fixed: https://skorch.readthedocs.io/en/docs-fix-broken-api-docs/callbacks.html
I'm not quite sure why the missing dependency wasn't a problem earlier but now is, but adding it should do no harm.
=> [skip ci] Try to fix broken API docs

skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py
- added version logging
- changed import order in one of the methods to avoid unnecessary warnings
=> Add version logging to NeptuneLogger

.github/workflows/testing.yml, README.rst, docs/user/installation.rst, setup.py, skorch/_doctor.py, skorch/tests/test_probabilistic.py
Since it is EOL this month anyway we should drop support and encourage users to upgrade to a more stable python branch.
I removed the TODOs related to python 3.7 to the best of my knowledge.
This is, in part, related to https://github.com/skorch-dev/skorch/pull/982 where `pkg_resources` is replaced with `importlib.metadata` which is only available in python 3.8.
=> Remove support for python 3.7

CHANGES.md, skorch/regressor.py, skorch/tests/test_regressor.py
This change makes it possible to pass a 1-dimensional y to `NeuralNetRegressor`.
Right now, skorch requires the `y` passed to `NeuralNetRegressor.fit` to be 2-dimensional, even if there is only one target, as is the most common case. This problem has come up a few times in the past, but mostly it's just an annoyance - just do `y.reshape(-1, 1)` and you're good (the error message says as much).
There are, however, also cases where it's not so easy to solve. For instance, in #972, a user reports that they cannot use skorch with sklearn's `BaggingRegressor`. The problem is that even if `y` is reshaped, once it is passed to the net from `BaggingRegressor`, it is 1d again. I assume that `BaggingRegressor` internally squeezes `y` at some point.
This PR lifts the 2d restriction check.
Why does …
=> Allow regression with 1d targets

scripts/deploy.sh
Before it was not possible to execute this script without errors as the conda update was broken. I moved the activation of the conda env to `conda run` which is apparently the recommended way.
=> This commit fixes the release/deploy script

.coveragerc
We vendor the code in `_version.py` from scipy. It is thus not necessary for us to have tests for it (it's tested in scipy). Still, it was included in the coverage report, resulting in artificially lowered test coverage. This fix removes the module from being counted for coverage.
=> Exclude _version.py from coverage report

docs/user/huggingface.rst, examples/accelerate-multigpu/README.md, examples/accelerate-multigpu/run-no-skorch.py, examples/accelerate-multigpu/run-with-skorch.py
There was an issue with using grid search, and other sklearn methods, that involve `clone`-ing, in conjunction with accelerate in a multi-gpu setting. This was due to sklearn creating copies of the `Accelerator` object. The skorch docs proposed a fix, but this fix is now released in accelerate itself. Therefore, the proposal can be safely removed.
Another minor change was to adjust the criterion in an example script. This is not essential for the script to work, but prevents `nan` losses.
=> Update docs after accelerate fix was released

CHANGES.md, examples/accelerate-multigpu/README.md, examples/accelerate-multigpu/run-save-load.py, skorch/hf.py, skorch/tests/test_hf.py
There were a few issue with saving and loading parameters for an accelerated net (some only in a multi-GPU setting though):
- `load_params` set the device if `device=None` to CPU, but we need `None` for accelerate
- not waiting for all processes to finish before saving parameters
- all processes saving the parameters, when only the main process should
- an issue with parameter names depending on the wrapping state
Regarding the last point, the issue was that if the module(s) are wrapped with accelerate, the parameters have an additional prefix, `"module."`. So e.g. `"dense0.weight"` would become `"module.dense0.weight"`. This could result in a key mismatch and error when loading a model.
The solution to this is to always unwrap the net before saving and before loading. That way, the extra …
=> FIX: Issues with saving/loading with accelerate

skorch/callbacks/lr_scheduler.py, skorch/hf.py, skorch/tests/callbacks/test_lr_scheduler.py, skorch/tests/test_hf.py
This PR makes 3 adjustments. Checking the individual commits may help with reviewing.
1. [Use accelerator.autocast when computing loss](https://github.com/skorch-dev/skorch/commit/c6b94cce548c7846cd13e35d5a32de66ebfc93da)
According to the accelerate docs, loss computation should be performed within the `accelerator.autocast` context manager:
https://huggingface.co/docs/accelerate/v0.21.0/en/quicktour#mixed-precision-training
I tested if this makes a difference by running the [this notebook](https://nbviewer.org/github/skorch-dev/skorch/blob/master/notebooks/Hugging_Face_Finetuning.ipynb) with fp16 precision.
I found no difference at all: The runtime was practically the same and the losses were identical. Still, I think it's better to have this than not, as it is recommended by the …
=> Accelerate some adjustment for mixed precision

requirements-dev.txt, skorch/tests/test_hf.py
In versions 0.20.* and 0.21.0 (latest), there was/is a bug in `unwrap_model` when called with `keep_fp32_wrapper=False`. This results in `forward` not working after unwrapping the model, which can affect skorch users who use `AccelerateMixin`.
The bug has been fixed in this PR:
https://github.com/huggingface/accelerate/pull/1838
However, there was no release yet. Therefore, I exclude the specific accelerate versions with that bug. Using a version <0.20 or a future release should work.
To catch this type of issue sooner, I added a test that will trigger the bug.
=> Accelerate bug in specific versions

setup.py
Ensures `requirements-dev.txt` is used if installed via `pip install -e .[testing]`
=> Fix install via test

docs/conf.py
Resolves #1018
Now always enforce the use of `sphinx_rtd_theme`. Previously, this was not done when the docs were built on RTD, instead using the default theme. I'm not really sure why that was so, maybe the default theme already was `sphinx_rtd_theme` but was changed later?
The docs after this change can be found here:
https://skorch.readthedocs.io/en/docs-try-fixing-rtd-theme/
At first I was suspicious if the change in `conf.py` was really the cause of the fix or if this was not instead somehow related to the `latest` version of the docs. Therefore, I created an empty PR #1020 and checked its docs. Those use the false theme, as can be witnessed here:
https://skorch.readthedocs.io/en/docs-experimental-branch-to-check-theme/
Therefore, I think the provided fix should also work for the …
=> DOC: Attempt at fixing theme on RTD

skorch/helper.py
`DataFrameTransformer` requires pandas but we don't want to have a dependency on pandas in skorch. Therefore, the pandas import should be local.
Back when I wrote this class, I thought it would be sufficient to import pandas at a class level, but that is incorrect. Now, pandas is important inside the method bodies.
For most skorch users, this should make no difference. But it will allow skorch users who use something from `helpers.py` to avoid having to install pandas.
=> FIX: Make pd import local in DataFrameTransformer

.github/workflows/testing.yml, README.rst, docs/user/installation.rst
At the same time, PyTorch 1.11.0 is no longer officially supported (though probably still works).
=> Add PyTorch v2.1.0 to officially supported version

.github/workflows/test-hf-integration.yml
For some reason, the existing install instruction started failing recently. Try a different one akin to what is used for the unit tests.
=> FIX: Torch install in HF integratin test workflow

skorch/callbacks/logging.py, skorch/tests/callbacks/test_logging.py
`pbar_` is only set in `on_epoch_begin`, so if `on_epoch_begin` is never called there will be a failure in saving the model.
=> Don't fail when pickling models which haven't been trained further

.github/workflows/test-hf-integration.yml
Explicitly set Python version to 3.11, was using 3.12 by default, which is not supported by PyTorch.
Also, update versions of checkout and setup-python GitHub actions.
=> FIX Python version in hf-integration test

skorch/hf.py
Since v0.20 of `huggingface_hub`, the attribute is a `CommitInfo` object (which is a `dataclass`), not a string anymore.
=> Fix return_url of HfApi client's upload_file method

skorch/callbacks/scoring.py, skorch/classifier.py, skorch/net.py, skorch/tests/test_classifier.py
Some skorch tests fail with sklearn v1.4. This commit fixes them:
1. Inheritance structure of scorers seems to have changed.
2. `classes_` attribute should always be numpy array
3. `CalibratedClassifierCV` only works with the output of `predict_proba` being float64
To fix the latter, I'm now casting the output of `predict_proba` to float64. However, I'm not sure if this is a good idea, as it might break existing code. I'm just adding it in for now to check if the tests pass.
**Update**: So the tests pass. Regarding the issue with `CalibratedClassifierCV` and float32, here are some suggestions:
1. Always cast to float64 and :crossed_fingers: that nothing breaks
2. Just keep float32 and skip the tests until the [sklearn fix](https://github.com/scikit-learn/scikit-learn/pull/28247) is …
=> Fix issues with sklearn 1.4

skorch/dataset.py
Following the issue I've presented in https://github.com/skorch-dev/skorch/issues/999
=> Fix invalid escape sequence '\s' in Dataset docstring

.github/workflows/testing.yml, README.rst, docs/user/installation.rst
Also:
- Remove 1.12.1
- Check 2.1.2 instead of 2.1.0
- Update docs
=> Add PyTorch 2.2.0 to CI

skorch/tests/test_net.py
We had a test that basically called `pytest.warns(None)`, which newer pytest versions don't allow. Instead, now using recwarn to assert that there is _no_ error.
The suggested `pytest.does_not_warn()` (pytest issues 9404) does not appear to work.
=> FIX New pytest version errors on warning test

CHANGES.md, skorch/tests/test_net.py, skorch/utils.py
Fixes #1057
`NeuralNetBinaryClassifier` was not working with `torch.compile` because the non-linearity was not correctly inferred. This inference depends on the instance type of the criterion. However, when using `torch.compile`, the criterion is wrapped, resulting in the `isinstance` check to miss. Now, we unwrap the criterion before checking the instance type.
=> FIX NeuralNetBinaryClassifier with torch.compile

.github/workflows/testing.yml
Pin numpy to < v2.0.0, as only PyTorch 2.3 and higher support it.
=> CI: Fix numpy version to below 2.0

skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
See discussion in #1063
Starting from PyTorch 2.4, there is a warning when `torch.load` is called without setting the weights_only argument. This is because in the future, the default will switch from `False` to `True`, which can result in a lot of errors when trying to load torch files (which are pickle files and thus insecure).
In this PR, we add a possibility for the user to influence the `kwargs` passed to `torch.load` so that they can control that behavior. If not further indicated by the user, we will use the same defaults as the installed torch version. Therefore, users will only encounter this issue via skorch if they would have encountered it via torch anyway.
Since it's not 100% certain if the default will switch in torch 2.6.0, we may have to adjust the version check in the …
=> Fix warning from torch.load starting in torch 2.4

.github/workflows/testing.yml, README.rst, docs/user/installation.rst, requirements-dev.txt, setup.py, skorch/tests/test_net.py, skorch/tests/test_regressor.py
* Drop 2.1.2, update 2.4.0 to 2.4.1
* Drop Python 3.8, add Python 3.12
* Filter new torch warning about `weights_only` as that trips up some warning tests
* Unpin protobuf from dev requirements
* Filter warnings caused by usage of `utcnow` by protobuf
* Skip `torch.compile` tests when torch < 2.4 and Python 3.12 are used, as this is not supported by torch
Note that I had to upgrade torch and Python at the same time because torch 2.5 requires Python > 3.8 and because Python 3.12 requires torch > 2.1 (which is dropped in favor of 2.5).
=> Add PyTorch 2.5.1 to CI

CHANGES.md, skorch/callbacks/base.py, skorch/classifier.py, skorch/hf.py, skorch/llm/classifier.py, skorch/net.py, skorch/probabilistic.py, skorch/regressor.py, skorch/tests/test_helper.py
Alternative to #1076
As described in that PR, skorch is currently not compatible with sklearn 1.6.0 or above. As per suggestion, instead of implementing `__sklearn_tags__`, this PR solves the issue by inheriting from `BaseEstimator`.
Related changes:
- It is important to set the correct order when inheriting from `BaseEstimator` and, say, `ClassifierMixin` (`BaseEstimator` should come last).
- As explained in #1076, using `GridSearchCV` with `y` being a torch tensor fails and two tests had to be adjusted.
Unrelated changes
- Removed unnecessary imports from `callbacks/base.py`.
=> Make skorch work with sklearn 1.6.0, attempt 2

CHANGES.md, skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
Previously, when using `ReduceLROnPlateau`, we would not record the learning rates in history. The code comment says that's because this class does not expose the `get_last_lr` method. I checked it again and it's now present, so let's use it.
Furthermore, I made a change to enable `ReduceLROnPlateau` to step on each batch (so far, only each epoch was supported). This is consistent with other learning rate schedulers.
=> ENH: ReduceLROnPlateau records the learning rate and works on batches

README.rst, setup.cfg
The readme renderer refuses to render scaled images (in this particular case, badges), as a result the [skorch PyPi page](https://pypi.org/project/skorch/0.2.0/) is displayed as plain text. This is easily fixed by removing scaling from badges in the README. On top of that, Explicitly specifying RST content type for the long description solves a warning during rendering.
See #1081 for more info.
=> Issue #1081: Fix PyPI Readme Rendering

skorch/callbacks/lr_scheduler.py, skorch/tests/callbacks/test_lr_scheduler.py
The purpose of this change is to allow for simulation of scheduling policies such as `ReduceLROnPlateau` to be simulated properly.
If `step_args` is an indexable object, it is indexed using the current simulated epoch to get closer to real-life behavior, e.g. simulating a real loss curve and the corresponding behavior of the LR scheduler policy.
=> Add step_args parameter to LRScheduler.simulate

skorch/classifier.py, skorch/regressor.py
Fixes parsing code so that documentation from NeuralNet is properly processed when adapting the documentation for NeuralNetClassifier, NeuralNetBinaryClassifier and NeuralNetRegressor classes in Python 3.13 and below.
See [Issue #1080 ](https://github.com/skorch-dev/skorch/issues/1080) for more details.
=> Issue #1080 : Fixing Parsing code for documentation retrieval in Python 3.13.

CHANGES.md, skorch/net.py, skorch/tests/test_net.py, skorch/utils.py
Resolves #1090, #1091.
This one got more complicated than I initially thought. So here it goes:
PyTorch plans to make the switch to `weights_only=True` for torch.load. We already partly dealt with that in #1064 when it comes to `save_params/load_params`. However, we still had a gap. Namely, when using pickle directly, i.e. when going through `__getstate__` and `__setstate__`, we are still using `torch.load` and `torch.save` without handling `weights_only`. This will cause trouble in the future when the default is switched. But it's also annoying right now, because users will get the `FutureWarning` about `weights_only`, even if they correctly pass `torch_load_kwargs` (see #1090).
The reason why we use `torch.save/torch.load` for pickle is that those functions are basically _extended_ …
=> FIX Unpickling without using torch.load

CHANGES.md, examples/optuna/README.md, examples/optuna/requirements.txt, examples/optuna/skorch_example.py
Fixes #718. 
As previously discussed, I have taken the example from the optuna-integration repo and fixed a couple of errors to ensure that the example runs correctly.
Output:
Number of finished trials: 100
Best trial:
Value: 0.9507142857142857
Params: 
n_layers: 1
dropout: 0.36848832612373067
n_units_l0: 104
Could you please review?
cc: @BenjaminBossan
=> Add Optuna Example for Skorch

CHANGES.md, CONTRIBUTING.rst
Fixes #229.
This is a follow-up to #1087. I've only switched to a different branch for contribution purposes.
Could you please review?
cc: @githubnemo ,@thomasjpfan
=> Add Contributing Guidelines

.github/workflows/testing.yml, README.rst, docs/user/installation.rst
- Dropped 2.3.1
- For PyTorch 2.6, install triton 3.2
- Drop numpy<2.0 install (no longer required for PyTorch)
=> Update: PyTorch v2.7.0

.github/workflows/test-hf-integration.yml
Due to #1108, `pip install -r requirements.txt` is no longer working. Also, I took the liberty to bump the Python version used to 3.12.
=> FIX: HF integration test workflow file

CHANGES.md, skorch/net.py, skorch/tests/test_classifier.py, skorch/tests/test_net.py, skorch/tests/test_regressor.py
Closes #1118 
Things to note:
- I saw the docstring [here](https://github.com/skorch-dev/skorch/blob/44c35271e9b82e136d998c16cc442d3e2204910f/skorch/hf.py#L66) so I made this `__sklearn_is_fitted__` docstring similar
- renamed the existing `test_not_fitted_raises` into `test_not_init_raises` but looking for advice on your preferences. 
- also not sure if a `test_not_fitted_raises` test is needed in all 3 of `tests/test_net.py`, `tests/test_regressor.py` and `tests/test_classifier.py` as the one in `tests/test_net.py` cover it. Again, seeking maintainers' preferences here. 
cc @BenjaminBossan
=> Custom sklearn estimators implementing `__sklearn_is_fitted__`
